import type { Pool } from "pg";
import type { StorageAdapter } from "@nexosophy/storage";
import {
  applyTemplateVariables, buildPortableManifest, claimNextDurableJob,
  completeDurableJob, completeTemplateUsage, completeTransfer,
  createNativeTextImport, failDurableJob, finalizePortableRelations,
  getImportAssetStorage, getTransfer, instantiatePortableNode,
  isTransferCancelled, loadTemplateSnapshotForUsage, mappedRootNodeIds,
  movePreviewOnlyImportNode, renderRichDocumentHtml, renderRichDocumentMarkdown,
  saveTemplateVersion, updateDurableJobProgress,
  type PortableManifest,
} from "@nexosophy/db";
import { createStoredZip, readStoredZipEntry } from "./zip-store.js";

type Logger={info:(x:any,m?:string)=>void;warn:(x:any,m?:string)=>void;error:(x:any,m?:string)=>void};
type Deps={pool:Pool;storage:StorageAdapter|null;workerId:string;logger:Logger;mediaProcessorUrl?:string;stopping:()=>boolean;delay:(ms:number)=>Promise<void>};

function parseManifest(v:unknown):PortableManifest{
  if(!v||typeof v!=="object")throw new Error("ARCHIVE_MANIFEST_INVALID");
  const m=v as PortableManifest;
  if(m.format!=="nexosophy-archive"||m.version!==1||!Array.isArray(m.nodes)||m.nodes.length>20000||!Array.isArray(m.relations))throw new Error("ARCHIVE_MANIFEST_INVALID");
  const ids=new Set<string>();for(const n of m.nodes){if(!n||typeof n.id!=="string"||!n.id||typeof n.name!=="string"||typeof n.kind!=="string"||ids.has(n.id))throw new Error("ARCHIVE_MANIFEST_INVALID");ids.add(n.id);}
  for(const n of m.nodes)if(n.parentId&&!ids.has(n.parentId))throw new Error("ARCHIVE_PARENT_MISSING");return m;
}
async function upload(storage:StorageAdapter,key:string,type:string,bytes:Uint8Array){const u=await storage.createUploadUrl({key,contentType:type,expiresInSeconds:900});const r=await fetch(u.url,{method:"PUT",headers:{"content-type":type,...(u.headers??{})},body:new Uint8Array(bytes)});if(!r.ok)throw new Error("EXPORT_UPLOAD_FAILED");}
async function download(storage:StorageAdapter,key:string,max:number){const u=await storage.createDownloadUrl({key,expiresInSeconds:900}),r=await fetch(u.url);if(!r.ok)throw new Error("IMPORT_DOWNLOAD_FAILED");const b=Buffer.from(await r.arrayBuffer());if(b.length>max)throw new Error("IMPORT_SOURCE_TOO_LARGE");return b;}
async function instantiate(deps:Deps,mode:{type:"transfer"|"template";id:string},w:string,u:string,p:string|null,m:PortableManifest,jobId:string,transferId?:string){
 let pending=[...m.nodes],done=0;while(pending.length){if(deps.stopping())throw new Error("WORKER_STOPPING");if(transferId&&await isTransferCancelled(deps.pool,transferId))throw new Error("TRANSFER_CANCELLED");const next:typeof pending=[];let progressed=0;for(const n of pending){try{await instantiatePortableNode(deps.pool,{mode,workspaceId:w,actorUserId:u,destinationParentId:p,node:n});done++;progressed++;if(done%25===0||done===m.nodes.length)await updateDurableJobProgress(deps.pool,jobId,{phase:"nodes",processed:done,total:m.nodes.length});}catch(e){if(e instanceof Error&&e.message==="IMPORT_PARENT_NOT_READY"){next.push(n);continue;}throw e;}}if(next.length&&!progressed)throw new Error("ARCHIVE_HIERARCHY_CYCLE");pending=next;}await finalizePortableRelations(deps.pool,{mode,workspaceId:w,actorUserId:u,relations:m.relations});return mappedRootNodeIds(deps.pool,mode,m);
}
function retryable(e:unknown){const c=e instanceof Error?e.message:"";return !["TRANSFER_CANCELLED","IMPORT_SOURCE_TOO_LARGE","ARCHIVE_MANIFEST_INVALID","ARCHIVE_PARENT_MISSING","ARCHIVE_HIERARCHY_CYCLE","ARCHIVE_ZIP_COMPRESSION_UNSUPPORTED","ARCHIVE_ZIP_CORRUPT","ARCHIVE_MANIFEST_NOT_FOUND","EXPORT_SOURCE_NOT_FOUND","EXPORT_FORMAT_REQUIRES_SINGLE_RICH_DOCUMENT","MEDIA_PROCESSOR_REQUIRED_FOR_PDF"].includes(c)&&!c.startsWith("TEMPLATE_")&&!c.startsWith("IMPORT_ASSET_NOT_");}
async function processJob(deps:Deps,job:any){
 if(job.jobType==="capture_template"){if(!job.workspaceId)throw new Error("TEMPLATE_WORKSPACE_REQUIRED");const templateId=String(job.payload.templateId??""),sourceNodeId=String(job.payload.sourceNodeId??""),actorUserId=String(job.payload.actorUserId??"");const manifest=await buildPortableManifest(deps.pool,{workspaceId:job.workspaceId,rootNodeId:sourceNodeId,scope:"template",includeRelations:true});const version=await saveTemplateVersion(deps.pool,{templateId,actorUserId,manifest,variables:Array.isArray(job.payload.variables)?job.payload.variables:[],publish:job.payload.publish===true});return completeDurableJob(deps.pool,job.id,{templateId,version,nodes:manifest.nodes.length});}
 if(job.jobType==="instantiate_template"){const usageId=String(job.payload.usageId??"");const x=await loadTemplateSnapshotForUsage(deps.pool,usageId),m=applyTemplateVariables(parseManifest(x.manifest),(x.usage.variable_values??{}) as Record<string,unknown>),w=String(x.usage.workspace_id),u=String(x.usage.requested_by_user_id),p=typeof x.usage.destination_parent_id==="string"?x.usage.destination_parent_id:null;const roots=await instantiate(deps,{type:"template",id:usageId},w,u,p,m,job.id);await completeTemplateUsage(deps.pool,{usageId,workspaceId:w,userId:u,rootNodeIds:roots});return completeDurableJob(deps.pool,job.id,{usageId,rootNodeIds:roots});}
 if(!job.workspaceId)throw new Error("TRANSFER_WORKSPACE_REQUIRED");const transferId=String(job.payload.transferId??""),t=await getTransfer(deps.pool,job.workspaceId,transferId);if(await isTransferCancelled(deps.pool,transferId))throw new Error("TRANSFER_CANCELLED");
 if(job.jobType==="import"){if(!t.sourceAssetId)throw new Error("IMPORT_ASSET_NOT_FOUND");const a=await getImportAssetStorage(deps.pool,job.workspaceId,t.sourceAssetId);if(t.fidelity==="preview_only"){const roots=await movePreviewOnlyImportNode(deps.pool,{transferId,workspaceId:job.workspaceId,actorUserId:t.requestedByUserId,assetNodeId:a.nodeId,destinationParentId:t.destinationParentId});await completeTransfer(deps.pool,{transferId,workspaceId:job.workspaceId,requestedByUserId:t.requestedByUserId,resultRootNodeIds:roots,fidelity:"preview_only"});return completeDurableJob(deps.pool,job.id,{rootNodeIds:roots,fidelity:"preview_only"});}
   if(!deps.storage)throw new Error("STORAGE_UNAVAILABLE");const b=await download(deps.storage,a.objectKey,t.format==="nexosophy"||t.format==="zip"?50*1024*1024:10*1024*1024);
   if(["markdown","text","csv","bibtex","ris"].includes(t.format)){const nodeId=await createNativeTextImport(deps.pool,{transferId,workspaceId:job.workspaceId,actorUserId:t.requestedByUserId,destinationParentId:t.destinationParentId,title:a.originalFilename.replace(/.[^.]+$/,""),text:b.toString("utf8"),format:t.format});await completeTransfer(deps.pool,{transferId,workspaceId:job.workspaceId,requestedByUserId:t.requestedByUserId,resultRootNodeIds:[nodeId],fidelity:t.fidelity});return completeDurableJob(deps.pool,job.id,{rootNodeIds:[nodeId]});}
   const m=parseManifest(JSON.parse((t.format==="zip"?readStoredZipEntry(b,"manifest.json"):b).toString("utf8"))),roots=await instantiate(deps,{type:"transfer",id:transferId},job.workspaceId,t.requestedByUserId,t.destinationParentId,m,job.id,transferId);await completeTransfer(deps.pool,{transferId,workspaceId:job.workspaceId,requestedByUserId:t.requestedByUserId,resultRootNodeIds:roots,fidelity:"portable_archive"});return completeDurableJob(deps.pool,job.id,{rootNodeIds:roots,nodes:m.nodes.length});
 }
 if(job.jobType==="export"){if(!deps.storage)throw new Error("STORAGE_UNAVAILABLE");const scope=t.options.scope==="workspace"?"workspace":"node",m=await buildPortableManifest(deps.pool,{workspaceId:job.workspaceId,rootNodeId:scope==="node"?t.sourceNodeId:null,scope,includeRelations:t.options.includeRelations!==false});const root=m.nodes.find(n=>n.parentId===null),stem=(root?.name??"workspace").replace(/[^A-Za-z0-9._-]+/g,"-").slice(0,120)||"nexosophy-export";let bytes:Buffer|undefined,filename="",mime="";
   if(t.format==="nexosophy"){bytes=Buffer.from(JSON.stringify(m,null,2));filename=stem+".nexo.json";mime="application/vnd.nexosophy.archive+json";}
   else if(t.format==="zip"){bytes=createStoredZip([{name:"manifest.json",data:Buffer.from(JSON.stringify(m,null,2))}]);filename=stem+".nexo.zip";mime="application/zip";}
   else {if(scope!=="node"||m.nodes.length!==1||!m.nodes[0]?.richDocument)throw new Error("EXPORT_FORMAT_REQUIRES_SINGLE_RICH_DOCUMENT");const n=m.nodes[0];if(t.format==="markdown"){bytes=Buffer.from(renderRichDocumentMarkdown(n.richDocument));filename=stem+".md";mime="text/markdown; charset=utf-8";}else if(t.format==="html"){bytes=Buffer.from(renderRichDocumentHtml(n.name,n.richDocument));filename=stem+".html";mime="text/html; charset=utf-8";}else if(t.format==="pdf"){throw new Error("MEDIA_PROCESSOR_REQUIRED_FOR_PDF");}else throw new Error("UNSUPPORTED_EXPORT_FORMAT");}
   const key="workspaces/"+job.workspaceId+"/transfers/"+transferId+"/"+filename;await upload(deps.storage,key,mime,bytes!);await completeTransfer(deps.pool,{transferId,workspaceId:job.workspaceId,requestedByUserId:t.requestedByUserId,artifactObjectKey:key,artifactFilename:filename,artifactMime:mime,fidelity:t.format==="nexosophy"||t.format==="zip"?"portable_archive":"partially_editable"});return completeDurableJob(deps.pool,job.id,{filename,bytes:bytes!.length});
 }
 throw new Error("TRANSFER_JOB_TYPE_UNKNOWN");
}
export async function runTransferLoop(deps:Deps){while(!deps.stopping()){const job=await claimNextDurableJob(deps.pool,"transfer",deps.workerId);if(!job){await deps.delay(500);continue;}try{await processJob(deps,job);}catch(e){if(e instanceof Error&&e.message==="TRANSFER_CANCELLED"){deps.logger.info({jobId:job.id},"Transfer cancelled");continue;}await failDurableJob(deps.pool,job.id,{code:e instanceof Error?e.message.split(":")[0]!.slice(0,120):"TRANSFER_JOB_FAILED",message:e instanceof Error?e.message:"Unknown transfer job failure.",retryable:retryable(e)});deps.logger.warn({err:e,jobId:job.id},"Transfer job failed");}}}
