export type FormulaValue=number|string|boolean|null;
type Token={t:"num"|"ref"|"id"|"op"|"lp"|"rp"|"comma";v:string};
function tokens(src:string):Token[]{const s=src.trim().replace(/^=/,"");const out:Token[]=[];let i=0;while(i<s.length){const c=s[i]!;if(/\s/.test(c)){i++;continue;}if(c==="{"){const e=s.indexOf("}",i+1);if(e<0)throw new Error("FORMULA_REF_UNCLOSED");out.push({t:"ref",v:s.slice(i+1,e)});i=e+1;continue;}if(/[0-9.]/.test(c)){let j=i+1;while(j<s.length&&/[0-9.eE+-]/.test(s[j]!)&&(!/[+-]/.test(s[j]!)||/[eE]/.test(s[j-1]!)))j++;const v=s.slice(i,j);if(!Number.isFinite(Number(v)))throw new Error("FORMULA_NUMBER_INVALID");out.push({t:"num",v});i=j;continue;}if(/[A-Za-z_]/.test(c)){let j=i+1;while(j<s.length&&/[A-Za-z0-9_]/.test(s[j]!))j++;out.push({t:"id",v:s.slice(i,j).toUpperCase()});i=j;continue;}const two=s.slice(i,i+2);if(["<=",">=","==","!="].includes(two)){out.push({t:"op",v:two});i+=2;continue;}if("+-*/%<>".includes(c)){out.push({t:"op",v:c});i++;continue;}if(c==="("){out.push({t:"lp",v:c});i++;continue;}if(c===")"){out.push({t:"rp",v:c});i++;continue;}if(c===","){out.push({t:"comma",v:c});i++;continue;}throw new Error("FORMULA_TOKEN_INVALID");}return out;}
function num(v:FormulaValue){if(typeof v==="number")return v;if(typeof v==="boolean")return v?1:0;if(v===null||v==="")return 0;const n=Number(v);if(!Number.isFinite(n))throw new Error("FORMULA_VALUE_NOT_NUMERIC");return n;}
export function formulaDependencies(src:string){return [...new Set(tokens(src).filter(x=>x.t==="ref").map(x=>x.v))];}
export function evaluateFormula(src:string,row:Record<string,FormulaValue>):FormulaValue{const ts=tokens(src);let p=0;const peek=()=>ts[p],take=()=>ts[p++];
 const primary=():FormulaValue=>{const t=take();if(!t)throw new Error("FORMULA_UNEXPECTED_END");if(t.t==="num")return Number(t.v);if(t.t==="ref")return row[t.v]??null;if(t.t==="op"&&(t.v==="+"||t.v==="-")){const v=num(primary());return t.v==="-"?-v:v;}if(t.t==="lp"){const v=cmp();if(take()?.t!=="rp")throw new Error("FORMULA_PAREN_MISSING");return v;}if(t.t==="id"){if(peek()?.t!=="lp")throw new Error("FORMULA_FUNCTION_PAREN");take();const args:FormulaValue[]=[];if(peek()?.t!=="rp"){while(true){args.push(cmp());if(peek()?.t==="comma"){take();continue;}break;}}if(take()?.t!=="rp")throw new Error("FORMULA_FUNCTION_CLOSE");switch(t.v){case"SUM":return args.reduce((a,b)=>a+num(b),0);case"AVG":return args.length?args.reduce((a,b)=>a+num(b),0)/args.length:0;case"MIN":return Math.min(...args.map(num));case"MAX":return Math.max(...args.map(num));case"ABS":return Math.abs(num(args[0]??0));case"ROUND":return Number(num(args[0]??0).toFixed(Math.max(0,Math.min(10,num(args[1]??0)))));case"IF":return Boolean(args[0])?(args[1]??null):(args[2]??null);default:throw new Error("FORMULA_FUNCTION_UNSUPPORTED");}}throw new Error("FORMULA_PRIMARY_INVALID");};
 const mul=():FormulaValue=>{let v=primary();while(peek()?.t==="op"&&["*","/","%"].includes(peek()!.v)){const op=take()!.v,r=num(primary()),l=num(v);v=op==="*"?l*r:op==="/"?r===0?null:l/r:r===0?null:l%r;}return v;};
 const add=():FormulaValue=>{let v=mul();while(peek()?.t==="op"&&["+","-"].includes(peek()!.v)){const op=take()!.v,r=mul();if(op==="+"&&(typeof v==="string"||typeof r==="string"))v=String(v??"")+String(r??"");else v=op==="+"?num(v)+num(r):num(v)-num(r);}return v;};
 const cmp=():FormulaValue=>{let v=add();if(peek()?.t==="op"&&["<",">","<=",">=","==","!="].includes(peek()!.v)){const op=take()!.v,r=add(),a=typeof v==="number"&&typeof r==="number"?v:String(v??""),b=typeof v==="number"&&typeof r==="number"?r:String(r??"");v=op==="=="?a===b:op==="!="?a!==b:op==="<"?a<b:op===">"?a>b:op==="<="?a<=b:a>=b;}return v;};
 const result=cmp();if(p!==ts.length)throw new Error("FORMULA_TRAILING_TOKENS");return result;
}
export function assertNoFormulaCycles(columns:Array<{key:string;formula:string|null}>){const graph=new Map(columns.map(c=>[c.key,c.formula?formulaDependencies(c.formula).filter(d=>columns.some(x=>x.key===d&&x.formula)):[]]));const visiting=new Set<string>(),done=new Set<string>();function dfs(k:string){if(done.has(k))return;if(visiting.has(k))throw new Error("FORMULA_CYCLE");visiting.add(k);for(const d of graph.get(k)??[])dfs(d);visiting.delete(k);done.add(k);}for(const k of graph.keys())dfs(k);}
