import type { Pool, PoolClient } from "pg";
import { withWorkspaceTransaction } from "./workspace-store-common.js";
export async function createEquipment(pool:Pool,input:{workspaceId:string;userId:string;name:string;category?:string;serialNumber?:string;locationId?:string;manualAssetId?:string;responsibleUserId?:string;trainingRequirement?:string;metadata:any}){const r=await pool.query<any>(`insert into "equipment" ("workspace_id","name","category","serial_number","location_id","manual_asset_id","responsible_user_id","training_requirement","metadata","created_by_user_id") values ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10) returning *`,[input.workspaceId,input.name,input.category??null,input.serialNumber??null,input.locationId??null,input.manualAssetId??null,input.responsibleUserId??null,input.trainingRequirement??null,JSON.stringify(input.metadata),input.userId]);return r.rows[0];}
export async function recordLabTraining(pool:Pool,input:{workspaceId:string;actorUserId:string;userId:string;requirement:string;completedAt:Date;validUntil?:Date;evidenceAssetId?:string}){const r=await pool.query<any>(`insert into "lab_training_records" ("workspace_id","user_id","requirement","completed_at","valid_until","evidence_asset_id","recorded_by_user_id") values ($1,$2,$3,$4,$5,$6,$7) returning *`,[input.workspaceId,input.userId,input.requirement,input.completedAt,input.validUntil??null,input.evidenceAssetId??null,input.actorUserId]);return r.rows[0];}
async function ensureEquipmentReady(db:PoolClient,w:string,equipmentId:string,userId:string,start:Date,end:Date){
 const e=await db.query<any>(`select * from "equipment" where "workspace_id"=$1 and "id"=$2 for update`,[w,equipmentId]);const x=e.rows[0];if(!x)throw new Error("EQUIPMENT_NOT_FOUND");if(["out_of_service","retired"].includes(x.status))throw new Error("EQUIPMENT_UNAVAILABLE");
 const overlap=await db.query(`select 1 from "equipment_bookings" where "workspace_id"=$1 and "equipment_id"=$2 and "status" in ('reserved','confirmed','checked_in') and tstzrange("starts_at","ends_at",'[)') && tstzrange($3,$4,'[)') limit 1`,[w,equipmentId,start,end]);if(overlap.rowCount)throw new Error("EQUIPMENT_BOOKING_CONFLICT");
 const maintenance=await db.query(`select 1 from "equipment_maintenance" where "workspace_id"=$1 and "equipment_id"=$2 and "status" in ('scheduled','in_progress') and tstzrange("starts_at",coalesce("ends_at","starts_at"+interval '24 hours'),'[)') && tstzrange($3,$4,'[)') limit 1`,[w,equipmentId,start,end]);if(maintenance.rowCount)throw new Error("MAINTENANCE_BOOKING_CONFLICT");
 const cal=await db.query<any>(`select * from "equipment_calibrations" where "workspace_id"=$1 and "equipment_id"=$2 order by "performed_at" desc limit 1`,[w,equipmentId]);if(cal.rows[0]?.valid_until&&new Date(cal.rows[0].valid_until)<end)throw new Error("CALIBRATION_EXPIRES_DURING_BOOKING");
 if(x.training_requirement){const t=await db.query(`select 1 from "lab_training_records" where "workspace_id"=$1 and "user_id"=$2 and "requirement"=$3 and ("valid_until" is null or "valid_until">=$4) order by "completed_at" desc limit 1`,[w,userId,x.training_requirement,start]);if(!t.rowCount)throw new Error("EQUIPMENT_TRAINING_REQUIRED");}
 return x;
}
export async function createEquipmentBooking(pool:Pool,input:{workspaceId:string;userId:string;equipmentId:string;startsAt:Date;endsAt:Date;timezone:string;experimentRunId?:string;purpose:string}){if(input.endsAt<=input.startsAt)throw new Error("BOOKING_TIME_INVALID");return withWorkspaceTransaction(pool,async db=>{await db.query(`select pg_advisory_xact_lock(hashtext($1),hashtext($2))`,[input.workspaceId,input.equipmentId]);await ensureEquipmentReady(db,input.workspaceId,input.equipmentId,input.userId,input.startsAt,input.endsAt);const r=await db.query<any>(`insert into "equipment_bookings" ("workspace_id","equipment_id","user_id","experiment_run_id","starts_at","ends_at","timezone","purpose") values ($1,$2,$3,$4,$5,$6,$7,$8) returning *`,[input.workspaceId,input.equipmentId,input.userId,input.experimentRunId??null,input.startsAt,input.endsAt,input.timezone,input.purpose]);return r.rows[0];});}
export async function updateBookingStatus(pool:Pool,input:{workspaceId:string;bookingId:string;userId:string;status:"confirmed"|"cancelled"}){const r=await pool.query<any>(`update "equipment_bookings" set "status"=$4::equipment_booking_status,"updated_at"=now() where "workspace_id"=$1 and "id"=$2 and ("user_id"=$3 or $4='cancelled') returning *`,[input.workspaceId,input.bookingId,input.userId,input.status]);if(!r.rows[0])throw new Error("BOOKING_NOT_FOUND");return r.rows[0];}
export async function checkInEquipment(pool:Pool,input:{workspaceId:string;bookingId:string;userId:string;notes:string}){return withWorkspaceTransaction(pool,async db=>{const b=await db.query<any>(`select * from "equipment_bookings" where "workspace_id"=$1 and "id"=$2 and "user_id"=$3 and "status" in ('reserved','confirmed') for update`,[input.workspaceId,input.bookingId,input.userId]);if(!b.rows[0])throw new Error("BOOKING_NOT_FOUND");await db.query(`update "equipment_bookings" set "status"='checked_in',"updated_at"=now() where "id"=$1`,[input.bookingId]);const u=await db.query<any>(`insert into "equipment_usage_logs" ("workspace_id","equipment_id","booking_id","user_id","checked_in_at","notes") values ($1,$2,$3,$4,now(),$5) returning *`,[input.workspaceId,b.rows[0].equipment_id,input.bookingId,input.userId,input.notes]);return u.rows[0];});}
export async function checkOutEquipment(pool:Pool,input:{workspaceId:string;bookingId:string;userId:string;notes:string}){return withWorkspaceTransaction(pool,async db=>{const b=await db.query<any>(`select * from "equipment_bookings" where "workspace_id"=$1 and "id"=$2 and "user_id"=$3 and "status"='checked_in' for update`,[input.workspaceId,input.bookingId,input.userId]);if(!b.rows[0])throw new Error("BOOKING_NOT_FOUND");await db.query(`update "equipment_bookings" set "status"='checked_out',"updated_at"=now() where "id"=$1`,[input.bookingId]);const u=await db.query<any>(`update "equipment_usage_logs" set "checked_out_at"=now(),"notes"=case when $4='' then "notes" else concat_ws(E'\n',"notes",$4) end where "workspace_id"=$1 and "booking_id"=$2 and "user_id"=$3 and "checked_out_at" is null returning *`,[input.workspaceId,input.bookingId,input.userId,input.notes]);return u.rows[0];});}
export async function createMaintenance(pool:Pool,input:{workspaceId:string;userId:string;equipmentId:string;kind:string;startsAt:Date;endsAt?:Date;description:string;performedBy?:string}){return withWorkspaceTransaction(pool,async db=>{await db.query(`select pg_advisory_xact_lock(hashtext($1),hashtext($2))`,[input.workspaceId,input.equipmentId]);const end=input.endsAt??new Date(input.startsAt.getTime()+86400000),overlap=await db.query(`select 1 from "equipment_bookings" where "workspace_id"=$1 and "equipment_id"=$2 and "status" in ('reserved','confirmed','checked_in') and tstzrange("starts_at","ends_at",'[)') && tstzrange($3,$4,'[)') limit 1`,[input.workspaceId,input.equipmentId,input.startsAt,end]);if(overlap.rowCount)throw new Error("MAINTENANCE_BOOKING_CONFLICT");const r=await db.query<any>(`insert into "equipment_maintenance" ("workspace_id","equipment_id","kind","starts_at","ends_at","description","performed_by","created_by_user_id") values ($1,$2,$3,$4,$5,$6,$7,$8) returning *`,[input.workspaceId,input.equipmentId,input.kind,input.startsAt,input.endsAt??null,input.description,input.performedBy??null,input.userId]);return r.rows[0];});}
export async function recordCalibration(pool:Pool,input:{workspaceId:string;userId:string;equipmentId:string;performedAt:Date;validUntil?:Date;result:string;certificateAssetId?:string;performedBy?:string}){const r=await pool.query<any>(`insert into "equipment_calibrations" ("workspace_id","equipment_id","performed_at","valid_until","result","certificate_asset_id","performed_by","created_by_user_id") values ($1,$2,$3,$4,$5,$6,$7,$8) returning *`,[input.workspaceId,input.equipmentId,input.performedAt,input.validUntil??null,input.result,input.certificateAssetId??null,input.performedBy??null,input.userId]);return r.rows[0];}
export async function equipmentDashboard(pool:Pool,w:string){const[e,b,m,c]=await Promise.all([pool.query<any>(`select * from "equipment" where "workspace_id"=$1 order by "name"`,[w]),pool.query<any>(`select b.*,e."name" as "equipment_name" from "equipment_bookings" b join "equipment" e on e."id"=b."equipment_id" where b."workspace_id"=$1 and b."ends_at">now()-interval '1 day' order by b."starts_at" limit 1000`,[w]),pool.query<any>(`select m.*,e."name" as "equipment_name" from "equipment_maintenance" m join "equipment" e on e."id"=m."equipment_id" where m."workspace_id"=$1 order by m."starts_at" desc limit 500`,[w]),pool.query<any>(`select c.*,e."name" as "equipment_name" from "equipment_calibrations" c join "equipment" e on e."id"=c."equipment_id" where c."workspace_id"=$1 order by c."performed_at" desc limit 500`,[w])]);return{equipment:e.rows,bookings:b.rows,maintenance:m.rows,calibrations:c.rows};}
export async function equipmentDetail(pool:Pool,w:string,id:string){const e=await pool.query<any>(`select * from "equipment" where "workspace_id"=$1 and "id"=$2`,[w,id]);if(!e.rows[0])throw new Error("EQUIPMENT_NOT_FOUND");const[b,u,m,c,t]=await Promise.all([pool.query<any>(`select * from "equipment_bookings" where "workspace_id"=$1 and "equipment_id"=$2 order by "starts_at" desc limit 500`,[w,id]),pool.query<any>(`select * from "equipment_usage_logs" where "workspace_id"=$1 and "equipment_id"=$2 order by "created_at" desc limit 500`,[w,id]),pool.query<any>(`select * from "equipment_maintenance" where "workspace_id"=$1 and "equipment_id"=$2 order by "starts_at" desc limit 500`,[w,id]),pool.query<any>(`select * from "equipment_calibrations" where "workspace_id"=$1 and "equipment_id"=$2 order by "performed_at" desc limit 500`,[w,id]),pool.query<any>(`select * from "lab_training_records" where "workspace_id"=$1 and "requirement"=$2 order by "completed_at" desc limit 500`,[w,e.rows[0].training_requirement??""])]);return{equipment:e.rows[0],bookings:b.rows,usage:u.rows,maintenance:m.rows,calibrations:c.rows,training:t.rows};}
