import { createHash, randomUUID } from "node:crypto";
import type { Pool } from "pg";
import { withWorkspaceTransaction } from "./workspace-store-common.js";
export async function createLabProtocol(pool:Pool,input:{workspaceId:string;userId:string;name:string;description:string;category?:string}){
 return withWorkspaceTransaction(pool,async db=>{const n=await db.query<{id:string}>(`insert into "content_nodes" ("workspace_id","kind","name","metadata","created_by_user_id","updated_by_user_id") values ($1,'lab_record',$2,$3::jsonb,$4,$4) returning "id"`,[input.workspaceId,input.name.slice(0,255),JSON.stringify({labRole:"protocol"}),input.userId]);await db.query(`insert into "documents" ("workspace_id","node_id","body","created_by_user_id","updated_by_user_id") values ($1,$2,$3::jsonb,$4,$4)`,[input.workspaceId,n.rows[0]!.id,JSON.stringify({type:"doc",blocks:[{id:randomUUID(),type:"heading",level:1,text:input.name},{id:randomUUID(),type:"paragraph",text:input.description}]}),input.userId]);const r=await db.query<any>(`insert into "protocols" ("workspace_id","name","description","category","node_id","created_by_user_id") values ($1,$2,$3,$4,$5,$6) returning *`,[input.workspaceId,input.name,input.description,input.category??null,n.rows[0]!.id,input.userId]);return r.rows[0];});
}
export async function createLabProtocolVersion(pool:Pool,input:{workspaceId:string;protocolId:string;userId:string;title:string;purpose:string;materials:any[];hazards:any[];expectedDurationMinutes?:number;changeReason?:string;steps:Array<{instruction:string;durationSeconds?:number;parameters:any;safetyNotes?:string}>}){
 return withWorkspaceTransaction(pool,async db=>{const p=await db.query<any>(`select * from "protocols" where "workspace_id"=$1 and "id"=$2 for update`,[input.workspaceId,input.protocolId]);if(!p.rows[0])throw new Error("PROTOCOL_NOT_FOUND");const n=await db.query<{n:string}>(`select (coalesce(max("version"),0)+1)::text as n from "protocol_versions" where "protocol_id"=$1`,[input.protocolId]),version=Number(n.rows[0]?.n??1);const v=await db.query<any>(`insert into "protocol_versions" ("protocol_id","version","title","purpose","materials","hazards","expected_duration_minutes","change_reason","created_by_user_id") values ($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7,$8,$9) returning *`,[input.protocolId,version,input.title,input.purpose,JSON.stringify(input.materials),JSON.stringify(input.hazards),input.expectedDurationMinutes??null,input.changeReason??null,input.userId]);for(const[position,s]of input.steps.entries())await db.query(`insert into "protocol_steps" ("protocol_version_id","position","instruction","duration_seconds","parameters","safety_notes") values ($1,$2,$3,$4,$5::jsonb,$6)`,[v.rows[0].id,position,s.instruction,s.durationSeconds??null,JSON.stringify(s.parameters),s.safetyNotes??null]);return v.rows[0];});
}
export async function approveLabProtocolVersion(pool:Pool,input:{workspaceId:string;protocolVersionId:string;userId:string;reason:string}){
 return withWorkspaceTransaction(pool,async db=>{const v=await db.query<any>(`select v.*,p."workspace_id",p."id" as "protocol_id_actual" from "protocol_versions" v join "protocols" p on p."id"=v."protocol_id" where p."workspace_id"=$1 and v."id"=$2 for update`,[input.workspaceId,input.protocolVersionId]);if(!v.rows[0])throw new Error("PROTOCOL_VERSION_NOT_FOUND");if(v.rows[0].status==="approved")return v.rows[0];const steps=await db.query<any>(`select "position","instruction","duration_seconds","parameters","safety_notes" from "protocol_steps" where "protocol_version_id"=$1 order by "position"`,[input.protocolVersionId]),hash=createHash("sha256").update(JSON.stringify({version:v.rows[0].version,title:v.rows[0].title,purpose:v.rows[0].purpose,materials:v.rows[0].materials,hazards:v.rows[0].hazards,steps:steps.rows})).digest("hex");const r=await db.query<any>(`update "protocol_versions" set "status"='approved',"approved_at"=now(),"approved_by_user_id"=$2,"content_hash"=$3 where "id"=$1 returning *`,[input.protocolVersionId,input.userId,hash]);await db.query(`insert into "protocol_approvals" ("protocol_version_id","approved_by_user_id","reason") values ($1,$2,$3)`,[input.protocolVersionId,input.userId,input.reason]);await db.query(`update "protocols" set "current_version"=greatest("current_version",$2),"updated_at"=now() where "id"=$1`,[v.rows[0].protocol_id_actual,v.rows[0].version]);await db.query(`insert into "lab_integrity_events" ("workspace_id","event_type","target_type","target_id","actor_user_id","reason","metadata") values ($1,'protocol.approved','protocol_version',$2,$3,$4,$5::jsonb)`,[input.workspaceId,input.protocolVersionId,input.userId,input.reason,JSON.stringify({contentHash:hash,version:v.rows[0].version})]);return r.rows[0];});
}
export async function acknowledgeProtocolVersion(pool:Pool,input:{workspaceId:string;protocolVersionId:string;userId:string}){const r=await pool.query(`insert into "protocol_acceptances" ("protocol_version_id","user_id") select v."id",$3 from "protocol_versions" v join "protocols" p on p."id"=v."protocol_id" where p."workspace_id"=$1 and v."id"=$2 and v."status"='approved' on conflict do nothing returning *`,[input.workspaceId,input.protocolVersionId,input.userId]);if(!r.rows[0]){const e=await pool.query(`select 1 from "protocol_acceptances" where "protocol_version_id"=$1 and "user_id"=$2`,[input.protocolVersionId,input.userId]);if(!e.rows[0])throw new Error("APPROVED_PROTOCOL_NOT_FOUND");}return{accepted:true};}
export async function listLabProtocols(pool:Pool,w:string){const r=await pool.query<any>(`select p.*,(select count(*) from "protocol_versions" v where v."protocol_id"=p."id")::int as "version_count" from "protocols" p where p."workspace_id"=$1 and p."archived_at" is null order by p."updated_at" desc,p."name"`,[w]);return r.rows;}
export async function getLabProtocol(pool:Pool,w:string,id:string,userId?:string){const p=await pool.query<any>(`select * from "protocols" where "workspace_id"=$1 and "id"=$2`,[w,id]);if(!p.rows[0])throw new Error("PROTOCOL_NOT_FOUND");const v=await pool.query<any>(`select v.*,exists(select 1 from "protocol_acceptances" a where a."protocol_version_id"=v."id" and a."user_id"=$2) as "accepted_by_me" from "protocol_versions" v where v."protocol_id"=$1 order by v."version" desc`,[id,userId??null]);const versions=[];for(const x of v.rows){const s=await pool.query<any>(`select * from "protocol_steps" where "protocol_version_id"=$1 order by "position"`,[x.id]);versions.push({...x,steps:s.rows});}return{protocol:p.rows[0],versions};}
export async function compareProtocolVersions(pool:Pool,w:string,id:string,a:number,b:number){const p=await pool.query(`select 1 from "protocols" where "workspace_id"=$1 and "id"=$2`,[w,id]);if(!p.rows[0])throw new Error("PROTOCOL_NOT_FOUND");const rows=await pool.query<any>(`select * from "protocol_versions" where "protocol_id"=$1 and "version"=any($2::integer[])`,[id,[a,b]]);if(rows.rows.length!==2)throw new Error("PROTOCOL_VERSION_NOT_FOUND");const result:any={};for(const v of rows.rows){const s=await pool.query<any>(`select "position","instruction","duration_seconds","parameters","safety_notes" from "protocol_steps" where "protocol_version_id"=$1 order by "position"`,[v.id]);result[v.version]={...v,steps:s.rows};}return{from:result[a],to:result[b],changedFields:Object.keys(result[a]??{}).filter(k=>JSON.stringify(result[a]?.[k])!==JSON.stringify(result[b]?.[k]))};}
export async function createExperimentRun(pool:Pool,input:{workspaceId:string;userId:string;experimentId:string;protocolVersionId?:string;parameters:any}){
 return withWorkspaceTransaction(pool,async db=>{const e=await db.query<any>(`select * from "lab_experiments" where "workspace_id"=$1 and "id"=$2 for update`,[input.workspaceId,input.experimentId]);if(!e.rows[0])throw new Error("EXPERIMENT_NOT_FOUND");if(input.protocolVersionId){const p=await db.query(`select 1 from "protocol_versions" v join "protocols" p on p."id"=v."protocol_id" where p."workspace_id"=$1 and v."id"=$2 and v."status"='approved'`,[input.workspaceId,input.protocolVersionId]);if(!p.rowCount)throw new Error("APPROVED_PROTOCOL_NOT_FOUND");}const n=await db.query<{n:string}>(`select (coalesce(max("run_number"),0)+1)::text as n from "experiment_runs" where "experiment_id"=$1`,[input.experimentId]);const r=await db.query<any>(`insert into "experiment_runs" ("workspace_id","experiment_id","protocol_version_id","run_number","parameters","created_by_user_id","updated_by_user_id") values ($1,$2,$3,$4,$5::jsonb,$6,$6) returning *`,[input.workspaceId,input.experimentId,input.protocolVersionId??null,Number(n.rows[0]?.n??1),JSON.stringify(input.parameters),input.userId]);return r.rows[0];});
}
export async function updateExperimentRun(pool:Pool,input:{workspaceId:string;runId:string;userId:string;expectedVersion:number;status?:string;parameters?:any;results?:any}){const r=await pool.query<any>(`update "experiment_runs" set "status"=coalesce($5::experiment_status,"status"),"parameters"=coalesce($6::jsonb,"parameters"),"results"=coalesce($7::jsonb,"results"),"started_at"=case when $5='running' and "started_at" is null then now() else "started_at" end,"completed_at"=case when $5 in ('completed','failed','cancelled') then now() else "completed_at" end,"version"="version"+1,"updated_by_user_id"=$3,"updated_at"=now() where "workspace_id"=$1 and "id"=$2 and "version"=$4 returning *`,[input.workspaceId,input.runId,input.userId,input.expectedVersion,input.status??null,input.parameters?JSON.stringify(input.parameters):null,input.results?JSON.stringify(input.results):null]);if(!r.rows[0])throw new Error("RUN_VERSION_CONFLICT");return r.rows[0];}
export async function addExperimentDeviation(pool:Pool,input:{workspaceId:string;runId:string;userId:string;description:string;reason:string}){const r=await pool.query<any>(`insert into "experiment_deviations" ("workspace_id","run_id","description","reason","created_by_user_id") select $1,r."id",$3,$4,$5 from "experiment_runs" r where r."workspace_id"=$1 and r."id"=$2 returning *`,[input.workspaceId,input.runId,input.description,input.reason,input.userId]);if(!r.rows[0])throw new Error("RUN_NOT_FOUND");return r.rows[0];}
