import { randomUUID } from "node:crypto";
import type { Pool,PoolClient } from "pg";
import { appendWorkspaceAudit,withWorkspaceTransaction } from "./workspace-store-common.js";
import { assertNoFormulaCycles,evaluateFormula,type FormulaValue } from "./formula-engine.js";

type StructuredColumn={id:string;key:string;name:string;type:string;formula:string|null;validation:Record<string,unknown>;options:string[];sortOrder:number;width:number;version:number;};
type RowRecord={id:string;position:number;values:Record<string,unknown>;computed:Record<string,FormulaValue>;version:number;createdAt:Date;updatedAt:Date;};

async function hist(c:PoolClient,w:string,n:string,event:string,payload:Record<string,unknown>,actor:string){
 await c.query(`insert into "specialized_history" ("workspace_id","node_id","event_type","payload","actor_user_id") values ($1,$2,$3,$4::jsonb,$5)`,[w,n,event,JSON.stringify(payload),actor]);
}
async function outbox(c:PoolClient,w:string,n:string,event:string,payload:Record<string,unknown>={}){
 await c.query(`insert into "outbox_events" ("workspace_id","aggregate_type","aggregate_id","event_type","payload") values ($1,'content',$2,$3,$4::jsonb)`,[w,n,event,JSON.stringify({nodeId:n,...payload})]);
}
async function insertNode(c:PoolClient,input:{workspaceId:string;actorUserId:string;parentId:string|null;kind:string;name:string;metadata:Record<string,unknown>}){
 if(input.parentId){const p=await c.query<{kind:string}>(`select "kind"::text as "kind" from "content_nodes" where "workspace_id"=$1 and "id"=$2 and "trashed_at" is null`,[input.workspaceId,input.parentId]);if(!p.rows[0])throw new Error("PARENT_NOT_FOUND");if(!["folder","notebook"].includes(p.rows[0].kind))throw new Error("PARENT_NOT_FOLDER");}
 const r=await c.query<{id:string}>(`insert into "content_nodes" ("workspace_id","parent_id","kind","name","metadata","created_by_user_id","updated_by_user_id") values ($1,$2,$3::content_node_kind,$4,$5::jsonb,$6,$6) returning "id"`,[input.workspaceId,input.parentId,input.kind,input.name.trim(),JSON.stringify(input.metadata),input.actorUserId]);return r.rows[0]!.id;
}
export async function createSpecializedNode(pool:Pool,input:{workspaceId:string;actorUserId:string;parentId:string|null;kind:"spreadsheet"|"database"|"code"|"notebook";name:string;language:string;requestId?:string;}){
 return withWorkspaceTransaction(pool,async c=>{const contentKind=input.kind==="spreadsheet"?"spreadsheet":input.kind==="database"?"dataset":input.kind==="notebook"?"notebook":"document";const metadata=input.kind==="code"?{editorType:"code",language:input.language}:input.kind==="notebook"?{notebookType:"computational"}:{editorType:"structured",structuredKind:input.kind};const nodeId=await insertNode(c,{workspaceId:input.workspaceId,actorUserId:input.actorUserId,parentId:input.parentId,kind:contentKind,name:input.name,metadata});
 if(input.kind==="spreadsheet"||input.kind==="database"){const d=await c.query<{id:string}>(`insert into "structured_documents" ("workspace_id","node_id","kind","created_by_user_id","updated_by_user_id") values ($1,$2,$3::structured_document_kind,$4,$4) returning "id"`,[input.workspaceId,nodeId,input.kind==="spreadsheet"?"sheet":"database",input.actorUserId]);const s=await c.query<{id:string}>(`insert into "structured_sheets" ("document_id","name") values ($1,'Sheet 1') returning "id"`,[d.rows[0]!.id]);await c.query(`insert into "structured_columns" ("sheet_id","key","name","type","sort_order") values ($1,'name','Name','text',0)`,[s.rows[0]!.id]);await c.query(`insert into "structured_views" ("document_id","name","type","config","created_by_user_id","updated_by_user_id") values ($1,'Default','table','{}'::jsonb,$2,$2)`,[d.rows[0]!.id,input.actorUserId]);}
 else if(input.kind==="code")await c.query(`insert into "code_documents" ("workspace_id","node_id","language","created_by_user_id","updated_by_user_id") values ($1,$2,$3,$4,$4)`,[input.workspaceId,nodeId,input.language,input.actorUserId]);
 else await c.query(`insert into "notebook_cells" ("workspace_id","node_id","position","type","source","created_by_user_id","updated_by_user_id") values ($1,$2,1024,'markdown','# New notebook',$3,$3)`,[input.workspaceId,nodeId,input.actorUserId]);
 await hist(c,input.workspaceId,nodeId,"specialized.created",{kind:input.kind},input.actorUserId);await outbox(c,input.workspaceId,nodeId,"specialized.created");await appendWorkspaceAudit(c,{workspaceId:input.workspaceId,actorUserId:input.actorUserId,action:"specialized.created",targetType:"node",targetId:nodeId,requestId:input.requestId,metadata:{kind:input.kind}});return{nodeId};});
}
async function columnsFor(c:Pool|PoolClient,sheetId:string):Promise<StructuredColumn[]>{const r=await c.query<any>(`select "id","key","name","type"::text as "type","formula","validation","options","sort_order","width","version" from "structured_columns" where "sheet_id"=$1 order by "sort_order","id"`,[sheetId]);return r.rows.map((x:any)=>({id:x.id,key:x.key,name:x.name,type:x.type,formula:x.formula,validation:x.validation??{},options:x.options??[],sortOrder:x.sort_order,width:x.width,version:x.version}));}
export async function getStructuredDocument(pool:Pool,w:string,nodeId:string){const d=await pool.query<any>(`select d.*,n."name" from "structured_documents" d join "content_nodes" n on n."workspace_id"=d."workspace_id" and n."id"=d."node_id" where d."workspace_id"=$1 and d."node_id"=$2 and n."trashed_at" is null`,[w,nodeId]);if(!d.rows[0])throw new Error("STRUCTURED_NOT_FOUND");const sheets=await pool.query<any>(`select * from "structured_sheets" where "document_id"=$1 order by "rank","id"`,[d.rows[0].id]);const views=await pool.query<any>(`select "id","name","type"::text as "type","config" from "structured_views" where "document_id"=$1 order by "created_at","id"`,[d.rows[0].id]);const charts=await pool.query<any>(`select "id","name","type"::text as "type","config" from "structured_charts" where "document_id"=$1 order by "created_at","id"`,[d.rows[0].id]);const out=[];for(const s of sheets.rows)out.push({id:s.id,name:s.name,rank:Number(s.rank),frozenRows:s.frozen_rows,frozenColumns:s.frozen_columns,columns:await columnsFor(pool,s.id)});return{id:d.rows[0].id,nodeId,kind:d.rows[0].kind,name:d.rows[0].name,settings:d.rows[0].settings??{},version:d.rows[0].version,sheets:out,views:views.rows,charts:charts.rows};}
function validValue(col:StructuredColumn,v:unknown){if(v===null||v===undefined||v==="")return;if(col.type==="number"&&typeof v!=="number")throw new Error("COLUMN_VALIDATION_NUMBER:"+col.key);if(col.type==="boolean"&&typeof v!=="boolean")throw new Error("COLUMN_VALIDATION_BOOLEAN:"+col.key);if(col.type==="date"&&Number.isNaN(new Date(String(v)).getTime()))throw new Error("COLUMN_VALIDATION_DATE:"+col.key);if(col.type==="select"&&col.options.length&&!col.options.includes(String(v)))throw new Error("COLUMN_VALIDATION_SELECT:"+col.key);const val=col.validation as any;if(typeof val.maxLength==="number"&&String(v).length>val.maxLength)throw new Error("COLUMN_VALIDATION_MAX_LENGTH:"+col.key);if(typeof val.min==="number"&&Number(v)<val.min)throw new Error("COLUMN_VALIDATION_MIN:"+col.key);if(typeof val.max==="number"&&Number(v)>val.max)throw new Error("COLUMN_VALIDATION_MAX:"+col.key);}
function compute(cols:StructuredColumn[],raw:Record<string,unknown>){const row:Record<string,FormulaValue>={};for(const c of cols)if(c.type!=="formula")row[c.key]=(raw[c.key]??null) as FormulaValue;let remaining=cols.filter(c=>c.type==="formula"&&c.formula);for(let i=0;i<cols.length&&remaining.length;i++){const next=[] as typeof remaining;for(const c of remaining){try{row[c.key]=evaluateFormula(c.formula!,row);}catch{next.push(c);}}if(next.length===remaining.length){for(const c of next)row[c.key]=null;break;}remaining=next;}return row;}
export async function listStructuredRows(pool:Pool,input:{workspaceId:string;nodeId:string;sheetId:string;cursor:number;limit:number;sortKey?:string;sortDir:"asc"|"desc";filterKey?:string;filterValue?:string;}){
 const cols=await columnsFor(pool,input.sheetId);const allowed=new Set(cols.map(c=>c.key));if(input.sortKey&&!allowed.has(input.sortKey))throw new Error("SORT_COLUMN_INVALID");if(input.filterKey&&!allowed.has(input.filterKey))throw new Error("FILTER_COLUMN_INVALID");const sort=input.sortKey?`coalesce("values"->>$4,'') ${input.sortDir==="desc"?"desc":"asc"},"position","id"`:'"position","id"';const values=[input.sheetId,input.cursor,input.limit+1,input.sortKey??null,input.filterKey??null,input.filterValue??null];const r=await pool.query<any>(`select "id","position","values","version","created_at","updated_at" from "structured_rows" where "sheet_id"=$1 and "position">$2 and ($5::text is null or lower(coalesce("values"->>$5,'')) like '%'||lower(coalesce($6,''))||'%') order by ${sort} limit $3`,values);const has=r.rows.length>input.limit,rows=r.rows.slice(0,input.limit).map((x:any)=>({id:x.id,position:Number(x.position),values:x.values??{},computed:compute(cols,x.values??{}),version:x.version,createdAt:x.created_at,updatedAt:x.updated_at} as RowRecord));return{items:rows,nextCursor:has?rows.at(-1)?.position??null:null};}
export async function createStructuredColumn(pool:Pool,input:{workspaceId:string;nodeId:string;sheetId:string;actorUserId:string;key:string;name:string;type:string;formula?:string|null;validation:Record<string,unknown>;options:string[];width:number;}){
 return withWorkspaceTransaction(pool,async c=>{const existing=await columnsFor(c,input.sheetId),candidate=[...existing,{id:"",key:input.key,name:input.name,type:input.type,formula:input.formula??null,validation:input.validation,options:input.options,sortOrder:existing.length,width:input.width,version:1}];assertNoFormulaCycles(candidate.map(x=>({key:x.key,formula:x.formula})));const r=await c.query<any>(`insert into "structured_columns" ("sheet_id","key","name","type","formula","validation","options","sort_order","width") values ($1,$2,$3,$4::structured_column_type,$5,$6::jsonb,$7::jsonb,$8,$9) returning *`,[input.sheetId,input.key,input.name,input.type,input.formula??null,JSON.stringify(input.validation),JSON.stringify(input.options),existing.length,input.width]);await hist(c,input.workspaceId,input.nodeId,"structured.column_created",{key:input.key,type:input.type},input.actorUserId);await outbox(c,input.workspaceId,input.nodeId,"structured.schema_changed");return r.rows[0];});
}
export async function upsertStructuredRow(pool:Pool,input:{workspaceId:string;nodeId:string;sheetId:string;rowId?:string;expectedVersion?:number;values:Record<string,unknown>;actorUserId:string;}){
 return withWorkspaceTransaction(pool,async c=>{const cols=await columnsFor(c,input.sheetId);for(const col of cols)if(col.type!=="formula"&&Object.prototype.hasOwnProperty.call(input.values,col.key))validValue(col,input.values[col.key]);let r;if(input.rowId){r=await c.query<any>(`update "structured_rows" set "values"="values"||$4::jsonb,"version"="version"+1,"updated_by_user_id"=$5,"updated_at"=now() where "sheet_id"=$1 and "id"=$2 and ($3::integer is null or "version"=$3) returning *`,[input.sheetId,input.rowId,input.expectedVersion??null,JSON.stringify(input.values),input.actorUserId]);if(!r.rows[0])throw new Error("ROW_VERSION_CONFLICT");}else{const pos=await c.query<{p:string}>(`select coalesce(max("position"),0)+1024 as p from "structured_rows" where "sheet_id"=$1`,[input.sheetId]);r=await c.query<any>(`insert into "structured_rows" ("sheet_id","position","values","created_by_user_id","updated_by_user_id") values ($1,$2,$3::jsonb,$4,$4) returning *`,[input.sheetId,Number(pos.rows[0]?.p??1024),JSON.stringify(input.values),input.actorUserId]);}await hist(c,input.workspaceId,input.nodeId,input.rowId?"structured.row_updated":"structured.row_created",{rowId:r.rows[0].id},input.actorUserId);await outbox(c,input.workspaceId,input.nodeId,"structured.rows_changed");return{id:r.rows[0].id,position:Number(r.rows[0].position),values:r.rows[0].values,computed:compute(cols,r.rows[0].values),version:r.rows[0].version};});
}
export async function createStructuredView(pool:Pool,input:{workspaceId:string;nodeId:string;documentId:string;actorUserId:string;name:string;type:string;config:Record<string,unknown>;}){return withWorkspaceTransaction(pool,async c=>{const r=await c.query<any>(`insert into "structured_views" ("document_id","name","type","config","created_by_user_id","updated_by_user_id") values ($1,$2,$3::structured_view_type,$4::jsonb,$5,$5) returning *`,[input.documentId,input.name,input.type,JSON.stringify(input.config),input.actorUserId]);await hist(c,input.workspaceId,input.nodeId,"structured.view_created",{viewId:r.rows[0].id,type:input.type},input.actorUserId);return r.rows[0];});}
export async function createStructuredChart(pool:Pool,input:{workspaceId:string;nodeId:string;documentId:string;actorUserId:string;name:string;type:"bar"|"line"|"pie";config:Record<string,unknown>;}){return withWorkspaceTransaction(pool,async c=>{const r=await c.query<any>(`insert into "structured_charts" ("document_id","name","type","config") values ($1,$2,$3::structured_chart_type,$4::jsonb) returning *`,[input.documentId,input.name,input.type,JSON.stringify(input.config)]);await hist(c,input.workspaceId,input.nodeId,"structured.chart_created",{chartId:r.rows[0].id},input.actorUserId);return r.rows[0];});}
export async function getCodeDocument(pool:Pool,w:string,nodeId:string){const r=await pool.query<any>(`select c.*,n."name" from "code_documents" c join "content_nodes" n on n."workspace_id"=c."workspace_id" and n."id"=c."node_id" where c."workspace_id"=$1 and c."node_id"=$2 and n."trashed_at" is null`,[w,nodeId]);if(!r.rows[0])throw new Error("CODE_NOT_FOUND");const x=r.rows[0];return{nodeId,name:x.name,language:x.language,source:x.source,schemaVersion:x.schema_version,version:x.version};}
export async function updateCodeDocument(pool:Pool,input:{workspaceId:string;nodeId:string;actorUserId:string;language:string;source:string;expectedVersion:number;}){return withWorkspaceTransaction(pool,async c=>{const r=await c.query<any>(`update "code_documents" set "language"=$4,"source"=$5,"version"="version"+1,"updated_by_user_id"=$3,"updated_at"=now() where "workspace_id"=$1 and "node_id"=$2 and "version"=$6 returning *`,[input.workspaceId,input.nodeId,input.actorUserId,input.language,input.source,input.expectedVersion]);if(!r.rows[0])throw new Error("CODE_VERSION_CONFLICT");await hist(c,input.workspaceId,input.nodeId,"code.saved",{language:input.language,version:r.rows[0].version},input.actorUserId);await outbox(c,input.workspaceId,input.nodeId,"code.saved");return{nodeId:input.nodeId,language:r.rows[0].language,source:r.rows[0].source,version:r.rows[0].version};});}
export async function getNotebook(pool:Pool,w:string,nodeId:string){const cells=await pool.query<any>(`select * from "notebook_cells" where "workspace_id"=$1 and "node_id"=$2 order by "position","id"`,[w,nodeId]);const out=await pool.query<any>(`select * from "notebook_outputs" where "workspace_id"=$1 and "node_id"=$2 order by "created_at","id"`,[w,nodeId]);return{cells:cells.rows.map((x:any)=>({id:x.id,position:Number(x.position),type:x.type,language:x.language,source:x.source,metadata:x.metadata??{},version:x.version,outputs:out.rows.filter((o:any)=>o.cell_id===x.id).map((o:any)=>({id:o.id,kind:o.kind,content:o.content,sizeBytes:o.size_bytes,createdAt:o.created_at}))}))};}
export async function createNotebookCell(pool:Pool,input:{workspaceId:string;nodeId:string;actorUserId:string;type:"markdown"|"code";language?:string;source:string;}){return withWorkspaceTransaction(pool,async c=>{const p=await c.query<{p:string}>(`select coalesce(max("position"),0)+1024 as p from "notebook_cells" where "workspace_id"=$1 and "node_id"=$2`,[input.workspaceId,input.nodeId]);const r=await c.query<any>(`insert into "notebook_cells" ("workspace_id","node_id","position","type","language","source","created_by_user_id","updated_by_user_id") values ($1,$2,$3,$4::notebook_cell_type,$5,$6,$7,$7) returning *`,[input.workspaceId,input.nodeId,Number(p.rows[0]?.p??1024),input.type,input.language??null,input.source,input.actorUserId]);await hist(c,input.workspaceId,input.nodeId,"notebook.cell_created",{cellId:r.rows[0].id,type:input.type},input.actorUserId);await outbox(c,input.workspaceId,input.nodeId,"notebook.changed");return r.rows[0];});}
export async function updateNotebookCell(pool:Pool,input:{workspaceId:string;nodeId:string;cellId:string;actorUserId:string;expectedVersion:number;type?:string;language?:string|null;source?:string;}){return withWorkspaceTransaction(pool,async c=>{const r=await c.query<any>(`update "notebook_cells" set "type"=coalesce($5::notebook_cell_type,"type"),"language"=case when $6::boolean then $7 else "language" end,"source"=coalesce($8,"source"),"version"="version"+1,"updated_by_user_id"=$4,"updated_at"=now() where "workspace_id"=$1 and "node_id"=$2 and "id"=$3 and "version"=$9 returning *`,[input.workspaceId,input.nodeId,input.cellId,input.actorUserId,input.type??null,input.language!==undefined,input.language??null,input.source??null,input.expectedVersion]);if(!r.rows[0])throw new Error("NOTEBOOK_CELL_VERSION_CONFLICT");await hist(c,input.workspaceId,input.nodeId,"notebook.cell_saved",{cellId:input.cellId,version:r.rows[0].version},input.actorUserId);await outbox(c,input.workspaceId,input.nodeId,"notebook.changed");return r.rows[0];});}
export async function reorderNotebookCells(pool:Pool,input:{workspaceId:string;nodeId:string;cellIds:string[];actorUserId:string;}){await withWorkspaceTransaction(pool,async c=>{for(const [i,id] of input.cellIds.entries())await c.query(`update "notebook_cells" set "position"=$4,"updated_by_user_id"=$3,"updated_at"=now() where "workspace_id"=$1 and "node_id"=$2 and "id"=$5`,[input.workspaceId,input.nodeId,input.actorUserId,(i+1)*1024,id]);await hist(c,input.workspaceId,input.nodeId,"notebook.reordered",{count:input.cellIds.length},input.actorUserId);});}
export async function clearNotebookOutputs(pool:Pool,input:{workspaceId:string;nodeId:string;cellId?:string;actorUserId:string;}){await withWorkspaceTransaction(pool,async c=>{await c.query(input.cellId?`delete from "notebook_outputs" where "workspace_id"=$1 and "node_id"=$2 and "cell_id"=$3`:`delete from "notebook_outputs" where "workspace_id"=$1 and "node_id"=$2`,input.cellId?[input.workspaceId,input.nodeId,input.cellId]:[input.workspaceId,input.nodeId]);await hist(c,input.workspaceId,input.nodeId,"notebook.outputs_cleared",{cellId:input.cellId??null},input.actorUserId);});}
export async function getExecutionPolicy(pool:Pool,w:string){const r=await pool.query<any>(`select "enabled","sandbox_provider","updated_at" from "workspace_execution_policy" where "workspace_id"=$1`,[w]);return r.rows[0]??{enabled:false,sandbox_provider:null,updated_at:null};}
export async function listSpecializedHistory(pool:Pool,w:string,nodeId:string,limit=100){const r=await pool.query<any>(`select "id","event_type","payload","actor_user_id","created_at" from "specialized_history" where "workspace_id"=$1 and "node_id"=$2 order by "id" desc limit $3`,[w,nodeId,Math.min(Math.max(limit,1),500)]);return r.rows;}
