"use client";import{Button}from"@nexosophy/ui";import{useCallback,useEffect,useState,type FormEvent}from"react";import styles from"./academic-hub.module.css";
async function get<T>(w:string,v="dashboard",x?:Record<string,string>){const q=new URLSearchParams({view:v,...(x??{})}),r=await fetch(`/api/academic/${w}?${q}`,{cache:"no-store"});if(!r.ok)throw new Error("Academic data failed to load.");return r.json() as Promise<T>;}async function post<T>(w:string,b:any){const r=await fetch(`/api/academic/${w}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b)});if(!r.ok){const x=await r.json().catch(()=>null) as any;throw new Error(x?.error?.message??"Academic action failed.");}return r.json() as Promise<T>;}
export function AcademicHub({workspaceId}:{workspaceId:string}){const[data,setData]=useState<any>(null),[due,setDue]=useState<any[]>([]),[tab,setTab]=useState("courses"),[status,setStatus]=useState("");const load=useCallback(async()=>{try{const[d,q]=await Promise.all([get<any>(workspaceId),get<any>(workspaceId,"due")]);setData(d);setDue(q.items??[]);setStatus("");}catch(e){setStatus(e instanceof Error?e.message:"Load failed.");}},[workspaceId]);useEffect(()=>{void load();},[load]);
 async function term(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await post(workspaceId,{action:"term",name:String(f.get("name")),code:String(f.get("code")||"")||undefined,startsOn:String(f.get("startsOn")),endsOn:String(f.get("endsOn"))});e.currentTarget.reset();void load();}catch(x){setStatus(x instanceof Error?x.message:"Term failed.");}}
 async function course(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await post(workspaceId,{action:"course",termId:String(f.get("termId")),name:String(f.get("name")),code:String(f.get("code")||"")||undefined,description:"",instructor:{name:String(f.get("instructor")||"")}});e.currentTarget.reset();void load();}catch(x){setStatus(x instanceof Error?x.message:"Course failed.");}}
 async function assignment(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),raw=String(f.get("dueAt")||"");try{await post(workspaceId,{action:"assignment",courseId:String(f.get("courseId")),title:String(f.get("title")),description:String(f.get("description")||""),dueAt:raw?new Date(raw).toISOString():undefined,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,priority:"medium",rubric:{}});e.currentTarget.reset();void load();}catch(x){setStatus(x instanceof Error?x.message:"Assignment failed.");}}
 async function exam(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),s=new Date(String(f.get("startsAt"))),end=new Date(s.getTime()+2*3600000);try{await post(workspaceId,{action:"exam",courseId:String(f.get("courseId")),title:String(f.get("title")),startsAt:s.toISOString(),endsAt:end.toISOString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,topics:String(f.get("topics")||"").split(",").map(x=>x.trim()).filter(Boolean),createRevisionTask:true});e.currentTarget.reset();void load();}catch(x){setStatus(x instanceof Error?x.message:"Exam failed.");}}
 async function deck(){const name=window.prompt("Deck name")?.trim(),courseId=window.prompt("Optional course ID")?.trim()||undefined;if(!name)return;try{await post(workspaceId,{action:"deck",name,courseId});void load();}catch(e){setStatus(e instanceof Error?e.message:"Deck failed.");}}
 async function card(){const deckId=window.prompt("Deck ID")?.trim(),front=window.prompt("Front")??"",back=window.prompt("Back")??"";if(!deckId||!front)return;try{await post(workspaceId,{action:"card",deckId,type:"basic",front,back,tags:[]});void load();}catch(e){setStatus(e instanceof Error?e.message:"Card failed.");}}
 async function review(id:string,grade:string){try{await post(workspaceId,{action:"review",cardId:id,grade});void load();}catch(e){setStatus(e instanceof Error?e.message:"Review failed.");}}
 const courses=data?.courses??[],terms=data?.terms??[],assignments=data?.assignments??[],exams=data?.exams??[];
 return <section className={styles.hub}><header className={styles.head}><div><p className="eyebrow">Student workspace</p><h1>Courses & study</h1><p>Terms, courses, canonical tasks/events, revision and spaced repetition.</p></div><div className={styles.stats}><span>{courses.length} courses</span><span>{assignments.filter((a:any)=>!["done","cancelled"].includes(a.task_status)).length} open assignments</span><span>{data?.dueCards??0} cards due</span></div></header><nav className={styles.tabs}>{["courses","assignments","exams","flashcards"].map(x=><button key={x} onClick={()=>setTab(x)} aria-current={tab===x?"page":undefined}>{x}</button>)}</nav>
 {tab==="courses"?<div className={styles.columns}><div className={styles.stack}><form className={styles.card} onSubmit={e=>void term(e)}><h2>New term</h2><label>Name<input name="name" required/></label><label>Code<input name="code"/></label><label>Starts<input type="date" name="startsOn" required/></label><label>Ends<input type="date" name="endsOn" required/></label><Button type="submit">Create term</Button></form><form className={styles.card} onSubmit={e=>void course(e)}><h2>New course</h2><label>Term<select name="termId" required><option value="">Choose…</option>{terms.map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Name<input name="name" required/></label><label>Code<input name="code"/></label><label>Instructor<input name="instructor"/></label><Button type="submit">Create course</Button></form></div><section className={styles.card}><h2>Courses</h2><div className={styles.list}>{courses.map((c:any)=><article key={c.id}><div><strong>{c.name}</strong><span>{c.code||"No code"} · {c.term_name}</span></div><a href={`/app/workspaces/${workspaceId}/academic/course/${c.id}`}>Open</a></article>)}</div></section></div>:null}
 {tab==="assignments"?<div className={styles.columns}><form className={styles.card} onSubmit={e=>void assignment(e)}><h2>New assignment</h2><label>Course<select name="courseId" required>{courses.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Title<input name="title" required/></label><label>Due<input type="datetime-local" name="dueAt"/></label><label>Description<textarea name="description"/></label><Button type="submit">Add assignment</Button></form><section className={styles.card}><h2>Assignments</h2><div className={styles.list}>{assignments.map((a:any)=><article key={a.id}><div><strong>{a.title}</strong><span>{a.course_name} · {a.task_status} · {a.due_at?new Date(a.due_at).toLocaleString():"No due date"}</span></div><a href="/app/tasks">Task</a></article>)}</div></section></div>:null}
 {tab==="exams"?<div className={styles.columns}><form className={styles.card} onSubmit={e=>void exam(e)}><h2>Schedule exam</h2><label>Course<select name="courseId" required>{courses.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Title<input name="title" required/></label><label>Starts<input type="datetime-local" name="startsAt" required/></label><label>Topics<input name="topics" placeholder="topic 1, topic 2"/></label><Button type="submit">Create exam + revision task</Button></form><section className={styles.card}><h2>Upcoming exams</h2><div className={styles.list}>{exams.map((x:any)=><article key={x.id}><div><strong>{x.title}</strong><span>{x.course_name} · {new Date(x.starts_at).toLocaleString()}</span></div><a href="/app/calendar">Calendar</a></article>)}</div></section></div>:null}
 {tab==="flashcards"?<div className={styles.columns}><section className={styles.card}><h2>Decks</h2><div className={styles.actions}><Button onClick={()=>void deck()}>New deck</Button><Button variant="secondary" onClick={()=>void card()}>New card</Button></div><div className={styles.list}>{(data?.decks??[]).map((d:any)=><article key={d.id}><div><strong>{d.name}</strong><span>{d.algorithm_version}</span><small>{d.id}</small></div></article>)}</div></section><section className={styles.card}><h2>Review queue</h2><div className={styles.review}>{due.map((c:any)=><article key={c.id}><strong>{c.front}</strong><details><summary>Show answer</summary><p>{c.back}</p></details><div className={styles.actions}>{["again","hard","good","easy"].map(g=><button key={g} onClick={()=>void review(c.id,g)}>{g}</button>)}</div></article>)}{!due.length?<p>No cards due.</p>:null}</div></section></div>:null}
 <p className={styles.live} aria-live="polite">{status}</p></section>}
