"use client";
import { Button } from "@nexosophy/ui";
import { useCallback,useEffect,useState,type FormEvent } from "react";
import styles from "./portability-hub.module.css";

type Template={id:string;name:string;description:string;scope:string;status:string;currentVersion:number;categoryName?:string|null;};
type Asset={id:string;nodeId:string|null;originalFilename:string;mimeType:string;sizeBytes:number;updatedAt:string;};
type Transfer={id:string;kind:"import"|"export";format:string;fidelity:string;artifactFilename:string|null;jobStatus:string|null;progress:Record<string,unknown>;resultRootNodeIds:string[];createdAt:string;};

async function get<T>(w:string,view:string,extra?:Record<string,string>){const q=new URLSearchParams({view,...(extra??{})}),r=await fetch(`/api/portability/${w}?${q}`,{cache:"no-store"});if(!r.ok)throw new Error("Request failed.");return r.json() as Promise<T>;}
async function post<T>(w:string,b:Record<string,unknown>){const r=await fetch(`/api/portability/${w}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b)});if(!r.ok){const x=await r.json().catch(()=>null) as any;throw new Error(x?.error?.message??"Request failed.");}if(r.status===204)return undefined as T;return r.json() as Promise<T>;}

export function PortabilityHub({workspaceId}:{workspaceId:string}){
 const[tab,setTab]=useState<"templates"|"import"|"export"|"activity">("templates"),[templates,setTemplates]=useState<Template[]>([]),[assets,setAssets]=useState<Asset[]>([]),[transfers,setTransfers]=useState<Transfer[]>([]),[status,setStatus]=useState("");
 const load=useCallback(async()=>{try{const[t,a,x]=await Promise.all([get<{items:Template[]}>(workspaceId,"templates"),get<{items:Asset[]}>(workspaceId,"assets"),get<{items:Transfer[]}>(workspaceId,"transfers")]);setTemplates(t.items);setAssets(a.items);setTransfers(x.items);}catch(e){setStatus(e instanceof Error?e.message:"Unable to load.");}},[workspaceId]);
 useEffect(()=>{void load();const id=window.setInterval(()=>void load(),5000);return()=>window.clearInterval(id);},[load]);

 async function createTemplate(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await post(workspaceId,{action:"createTemplate",name:String(f.get("name")??""),description:String(f.get("description")??""),scope:String(f.get("scope")??"personal"),sourceNodeId:String(f.get("sourceNodeId")??""),roleSuggestions:String(f.get("roles")??"").split(",").map(x=>x.trim()).filter(Boolean),variables:[],publish:f.get("publish")==="on"});setStatus("Template capture queued.");e.currentTarget.reset();void load();}catch(x){setStatus(x instanceof Error?x.message:"Template failed.");}}
 async function instantiateTemplate(t:Template){const valuesText=window.prompt("Template variable values as JSON","{}");if(valuesText===null)return;let values={};try{values=JSON.parse(valuesText);}catch{setStatus("Variable JSON is invalid.");return;}try{await post(workspaceId,{action:"instantiate",templateId:t.id,values,destinationParentId:null});setStatus("Template instantiation queued.");void load();}catch(e){setStatus(e instanceof Error?e.message:"Instantiation failed.");}}
 async function importAsset(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await post(workspaceId,{action:"import",assetId:String(f.get("assetId")??""),destinationParentId:null});setStatus("Import queued.");void load();}catch(x){setStatus(x instanceof Error?x.message:"Import failed.");}}
 async function exportData(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),scope=String(f.get("scope")??"workspace"),nodeId=String(f.get("nodeId")??"").trim();try{await post(workspaceId,{action:"export",scope,nodeId:scope==="node"?nodeId:undefined,format:String(f.get("format")??"nexosophy"),includeRelations:true});setStatus("Export queued.");void load();}catch(x){setStatus(x instanceof Error?x.message:"Export failed.");}}
 async function action(t:Transfer,a:"cancel"|"retry"){try{await post(workspaceId,{action:a,transferId:t.id});setStatus(a==="cancel"?"Transfer cancelled.":"Transfer requeued.");void load();}catch(e){setStatus(e instanceof Error?e.message:"Action failed.");}}
 async function download(t:Transfer){try{const x=await get<{url:string}>(workspaceId,"download",{transferId:t.id});window.location.assign(x.url);}catch(e){setStatus(e instanceof Error?e.message:"Download unavailable.");}}

 return <section className={styles.hub}>
  <header className={styles.head}><div><p className="eyebrow">Reuse & portability</p><h1>Templates, import & export</h1><p>Portable archives, explicit fidelity labels, durable transfers, and private signed downloads.</p></div></header>
  <nav className={styles.tabs}>{(["templates","import","export","activity"] as const).map(x=><button type="button" key={x} onClick={()=>setTab(x)} aria-current={tab===x?"page":undefined}>{x}</button>)}</nav>
  {tab==="templates"?<div className={styles.grid}>
    <form className={styles.card} onSubmit={e=>void createTemplate(e)}><h2>Save as template</h2><label>Name<input name="name" required/></label><label>Source node ID<input name="sourceNodeId" required/></label><label>Description<textarea name="description"/></label><label>Scope<select name="scope"><option value="personal">Personal</option><option value="workspace">Workspace</option></select></label><label>Suggested roles<input name="roles" placeholder="student, researcher"/></label><label className={styles.inline}><input type="checkbox" name="publish"/> Publish immediately</label><Button type="submit">Capture template</Button></form>
    <section className={styles.card}><h2>Gallery</h2><div className={styles.list}>{templates.map(t=><article key={t.id}><div><strong>{t.name}</strong><span>{t.scope} · {t.status} · v{t.currentVersion}</span><p>{t.description}</p></div><Button variant="secondary" onClick={()=>void instantiateTemplate(t)} disabled={!t.currentVersion}>Use</Button></article>)}{!templates.length?<p>No templates yet.</p>:null}</div></section>
  </div>:null}
  {tab==="import"?<form className={styles.card} onSubmit={e=>void importAsset(e)}><h2>Import trusted upload</h2><p>Native text/CSV/BibTeX/RIS become editable. Office/PDF/media stay preview-only unless a converter is configured.</p><label>Uploaded asset<select name="assetId" required><option value="">Choose…</option>{assets.map(a=><option key={a.id} value={a.id}>{a.originalFilename} · {(a.sizeBytes/1024/1024).toFixed(1)} MB</option>)}</select></label><Button type="submit">Start import</Button></form>:null}
  {tab==="export"?<form className={styles.card} onSubmit={e=>void exportData(e)}><h2>Export content</h2><label>Scope<select name="scope"><option value="workspace">Whole workspace</option><option value="node">Single node/subtree</option></select></label><label>Node ID<input name="nodeId" placeholder="Required for node scope"/></label><label>Format<select name="format"><option value="nexosophy">Nexosophy archive JSON</option><option value="zip">Nexosophy ZIP</option><option value="markdown">Markdown (single rich document)</option><option value="html">HTML (single rich document)</option><option value="pdf">PDF (requires converter)</option></select></label><Button type="submit">Queue export</Button></form>:null}
  {tab==="activity"?<section className={styles.card}><h2>Transfer activity</h2><div className={styles.list}>{transfers.map(t=><article key={t.id}><div><strong>{t.kind} · {t.format}</strong><span>{t.jobStatus??"pending"} · {t.fidelity}</span><p>{JSON.stringify(t.progress)}</p></div><div className={styles.actions}>{t.artifactFilename?<Button variant="secondary" onClick={()=>void download(t)}>Download</Button>:null}{["queued","running"].includes(t.jobStatus??"")?<button type="button" onClick={()=>void action(t,"cancel")}>Cancel</button>:null}{["failed","dead_letter","cancelled"].includes(t.jobStatus??"")?<button type="button" onClick={()=>void action(t,"retry")}>Retry</button>:null}</div></article>)}</div></section>:null}
  <p className={styles.live} aria-live="polite">{status}</p>
 </section>;
}
