"use client";
import {Button} from "@nexosophy/ui";
import {useCallback,useEffect,useState,type FormEvent} from "react";
import styles from "./research-reference-hub.module.css";

async function get<T>(w:string,view:string,extra?:Record<string,string>){const q=new URLSearchParams({view,...(extra??{})}),r=await fetch(`/api/research/${w}?${q}`,{cache:"no-store"});if(!r.ok)throw new Error("Research data failed to load.");return r.json() as Promise<T>;}
async function post<T>(w:string,b:any){const r=await fetch(`/api/research/${w}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b)});if(!r.ok){const x=await r.json().catch(()=>null) as any;throw new Error(x?.error?.message??"Research action failed.");}return r.json() as Promise<T>;}

export function ResearchReferenceHub({workspaceId,initialTab="thesis"}:{workspaceId:string;initialTab?:"thesis"|"references"|"import-export"}){
 const[tab,setTab]=useState(initialTab),[dashboard,setDashboard]=useState<any>(null),[refs,setRefs]=useState<any[]>([]),[q,setQ]=useState(""),[status,setStatus]=useState("");
 const load=useCallback(async()=>{try{const[d,r]=await Promise.all([get<any>(workspaceId,"dashboard"),get<any>(workspaceId,"references",{q,limit:"200"})]);setDashboard(d);setRefs(r.items??[]);setStatus("");}catch(e){setStatus(e instanceof Error?e.message:"Load failed.");}},[workspaceId,q]);
 useEffect(()=>{void load();},[load]);

 async function thesis(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),supervisor=String(f.get("supervisor")||"").trim();try{await post(workspaceId,{action:"thesis",title:String(f.get("title")),degree:String(f.get("degree")||"")||undefined,field:String(f.get("field")||"")||undefined,proposal:String(f.get("proposal")||""),supervisors:supervisor?[{name:supervisor,role:"supervisor"}]:[]});e.currentTarget.reset();void load();}catch(x){setStatus(x instanceof Error?x.message:"Thesis creation failed.");}}
 async function reference(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),authors=String(f.get("authors")||"").split(";").map(x=>x.trim()).filter(Boolean).map(literal=>({literal})),doi=String(f.get("doi")||"").trim();try{await post(workspaceId,{action:"reference",type:String(f.get("type")||"article"),title:String(f.get("title")),year:Number(f.get("year"))||undefined,containerTitle:String(f.get("containerTitle")||"")||undefined,url:String(f.get("url")||"")||undefined,authors,identifiers:doi?[{type:"doi",value:doi}]:[],metadata:{}});e.currentTarget.reset();void load();}catch(x){setStatus(x instanceof Error?x.message:"Reference failed.");}}
 async function resolve(){const value=window.prompt("DOI / ISBN / PMID / arXiv identifier")?.trim();if(!value)return;const type=window.prompt("Type: doi, isbn, pmid, arxiv","doi")?.trim()||"doi";try{const x=await post<any>(workspaceId,{action:"resolve",type,value});setStatus(x.status==="local"?"Identifier already exists in this library.":"Identifier normalized. External metadata provider can be attached to the provider boundary later.");}catch(e){setStatus(e instanceof Error?e.message:"Resolve failed.");}}
 async function annotation(ref:any){const comment=window.prompt("Annotation / note")??"";if(!comment)return;const quote=window.prompt("Optional quote")||undefined;try{await post(workspaceId,{action:"annotation",referenceId:ref.id,comment,quote});setStatus("Annotation saved.");}catch(e){setStatus(e instanceof Error?e.message:"Annotation failed.");}}
 async function matrix(ref:any){const findings=window.prompt("Key findings")??"";const method=window.prompt("Method")??"";const relevance=window.prompt("Relevance to your research")??"";const projectId=window.prompt("Optional thesis project ID")?.trim()||undefined;try{await post(workspaceId,{action:"matrix",referenceId:ref.id,projectId,findings,method,relevance});setStatus("Literature matrix updated.");}catch(e){setStatus(e instanceof Error?e.message:"Matrix update failed.");}}
 async function attach(ref:any){const assetId=window.prompt("Trusted PDF/file asset ID")?.trim();if(!assetId)return;try{await post(workspaceId,{action:"attach",referenceId:ref.id,assetId,label:window.prompt("Attachment label","PDF")||undefined});setStatus("Attachment linked.");}catch(e){setStatus(e instanceof Error?e.message:"Attachment failed.");}}
 async function merge(ref:any){const other=window.prompt("Reference ID to merge into this reference")?.trim();if(!other)return;if(!window.confirm("Merge the other reference into this canonical record?"))return;try{await post(workspaceId,{action:"merge",keepReferenceId:ref.id,mergeReferenceId:other});setStatus("References merged.");void load();}catch(e){setStatus(e instanceof Error?e.message:"Merge failed.");}}
 async function collection(){const name=window.prompt("Collection name")?.trim();if(!name)return;try{const x=await post<any>(workspaceId,{action:"collection",name,projectId:window.prompt("Optional thesis project ID")?.trim()||undefined});setStatus("Collection created: "+x.id);}catch(e){setStatus(e instanceof Error?e.message:"Collection failed.");}}
 async function addToCollection(ref:any){const collectionId=window.prompt("Collection ID")?.trim();if(!collectionId)return;try{await post(workspaceId,{action:"collectionItem",collectionId,referenceId:ref.id});setStatus("Reference added to collection.");}catch(e){setStatus(e instanceof Error?e.message:"Collection update failed.");}}
 async function bibliography(){try{const x=await get<any>(workspaceId,"bibliography",{styleId:"apa7"});setStatus("Bibliography generated: "+x.items.length+" entries. Open browser console/copy through export when needed.");console.log("Nexosophy bibliography",x.items);}catch(e){setStatus(e instanceof Error?e.message:"Bibliography failed.");}}
 async function importText(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const x=await post<any>(workspaceId,{action:"import",format:String(f.get("format")),text:String(f.get("text"))});setStatus(`Imported ${x.imported} reference(s).`);void load();}catch(e){setStatus(e instanceof Error?e.message:"Import failed.");}}
 async function exportText(format:"bibtex"|"ris"){try{const x=await get<{filename:string;text:string}>(workspaceId,"export",{format});const blob=new Blob([x.text],{type:"text/plain"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=x.filename;a.click();URL.revokeObjectURL(url);}catch(e){setStatus(e instanceof Error?e.message:"Export failed.");}}

 return <section className={styles.hub}><header className={styles.head}><div><p className="eyebrow">Research & postgraduate</p><h1>Thesis and references</h1><p>Long-form research planning, traceable references, literature synthesis and citation insertion.</p></div><div className={styles.stats}><span>{dashboard?.projects?.length??0} thesis projects</span><span>{dashboard?.referenceCount??0} references</span></div></header><nav className={styles.tabs}>{(["thesis","references","import-export"] as const).map(x=><button key={x} aria-current={tab===x?"page":undefined} onClick={()=>setTab(x)}>{x}</button>)}</nav>
 {tab==="thesis"?<div className={styles.columns}><form className={styles.card} onSubmit={e=>void thesis(e)}><h2>New thesis / dissertation</h2><label>Title<input name="title" required/></label><label>Degree<input name="degree" placeholder="MSc / PhD"/></label><label>Field<input name="field"/></label><label>Supervisor<input name="supervisor"/></label><label>Proposal<textarea name="proposal" rows={7}/></label><Button type="submit">Create research workspace</Button></form><section className={styles.card}><h2>Projects</h2><div className={styles.list}>{dashboard?.projects?.map((p:any)=><article key={p.id}><div><strong>{p.title}</strong><span>{p.status} · {p.chapter_count} chapters · {p.checklist_done}/{p.checklist_total} checklist</span></div><a href={`/app/workspaces/${workspaceId}/research/thesis/${p.id}`}>Open</a></article>)}</div></section></div>:null}
 {tab==="references"?<div className={styles.columns}><form className={styles.card} onSubmit={e=>void reference(e)}><h2>Add reference</h2><label>Type<select name="type"><option value="article">Article</option><option value="book">Book</option><option value="thesis">Thesis</option><option value="conference">Conference</option><option value="web">Web</option><option value="dataset">Dataset</option></select></label><label>Title<input name="title" required/></label><label>Authors<input name="authors" placeholder="Author One; Author Two"/></label><label>Year<input name="year" type="number"/></label><label>Journal / container<input name="containerTitle"/></label><label>DOI<input name="doi"/></label><label>URL<input name="url" type="url"/></label><div className={styles.actions}><Button type="submit">Add reference</Button><Button type="button" variant="secondary" onClick={()=>void resolve()}>Resolve identifier</Button></div></form><section className={styles.card}><header className={styles.search}><h2>Library</h2><input value={q} onChange={e=>setQ(e.currentTarget.value)} placeholder="Search title, abstract, identifier…"/><div className={styles.actions}><Button type="button" variant="secondary" onClick={()=>void collection()}>New collection</Button><Button type="button" variant="secondary" onClick={()=>void bibliography()}>Generate bibliography</Button></div></header><div className={styles.list}>{refs.map((r:any)=><article key={r.id}><div><strong>{r.title}</strong><span>{r.authors?.map((a:any)=>a.literal??a.family).filter(Boolean).join(", ")} {r.year?"· "+r.year:""}</span><small>{r.identifiers?.map((i:any)=>i.type.toUpperCase()+": "+i.value).join(" · ")}</small></div><div className={styles.actions}><a href={`/app/workspaces/${workspaceId}/research/reference/${r.id}`}>Open</a><button onClick={()=>void annotation(r)}>Annotate</button><button onClick={()=>void matrix(r)}>Matrix</button><button onClick={()=>void attach(r)}>Attach PDF</button><button onClick={()=>void addToCollection(r)}>Collection</button><button onClick={()=>void merge(r)}>Merge</button></div></article>)}</div></section></div>:null}
 {tab==="import-export"?<div className={styles.columns}><form className={styles.card} onSubmit={e=>void importText(e)}><h2>Import bibliography</h2><label>Format<select name="format"><option value="bibtex">BibTeX</option><option value="ris">RIS</option></select></label><label>Bibliography text<textarea name="text" rows={18} required/></label><Button type="submit">Import references</Button></form><section className={styles.card}><h2>Export bibliography</h2><p>Export canonical library records with authors and identifiers.</p><div className={styles.actions}><Button onClick={()=>void exportText("bibtex")}>Export BibTeX</Button><Button variant="secondary" onClick={()=>void exportText("ris")}>Export RIS</Button></div></section></div>:null}
 <p className={styles.live} aria-live="polite">{status}</p></section>;
}
