"use client";
import {Button} from "@nexosophy/ui";
import {useCallback,useEffect,useMemo,useState} from "react";
import styles from "./specialized-editor.module.css";

async function get<T>(w:string,v:string,nodeId:string,q?:URLSearchParams){const p=q??new URLSearchParams();p.set("view",v);p.set("nodeId",nodeId);const r=await fetch(`/api/specialized/${w}?${p}`,{cache:"no-store"});if(!r.ok)throw new Error("Load failed.");return r.json() as Promise<T>;}
async function post<T>(w:string,b:any){const r=await fetch(`/api/specialized/${w}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b)});if(!r.ok){const x=await r.json().catch(()=>null) as any;throw new Error(x?.error?.message??"Save failed.");}if(r.status===204)return undefined as T;return r.json() as Promise<T>;}

export function StructuredDataEditor({workspaceId,nodeId}:{workspaceId:string;nodeId:string}){
 const[doc,setDoc]=useState<any>(null),[sheetId,setSheetId]=useState(""),[rows,setRows]=useState<any[]>([]),[status,setStatus]=useState("Loading…"),[filter,setFilter]=useState("");
 const load=useCallback(async()=>{try{const d=await get<any>(workspaceId,"structured",nodeId);setDoc(d);const sid=sheetId||d.sheets?.[0]?.id||"";setSheetId(sid);if(sid){const q=new URLSearchParams({sheetId:sid,limit:"200"});if(filter){q.set("filterKey","name");q.set("filterValue",filter);}const r=await get<any>(workspaceId,"rows",nodeId,q);setRows(r.items??[]);}setStatus("");}catch(e){setStatus(e instanceof Error?e.message:"Load failed.");}},[workspaceId,nodeId,sheetId,filter]);
 useEffect(()=>{void load();},[load]);
 const sheet=useMemo(()=>doc?.sheets?.find((s:any)=>s.id===sheetId),[doc,sheetId]);
 async function addColumn(){const key=window.prompt("Column key (letters/numbers/_)", "value")?.trim();if(!key||!sheetId)return;const name=window.prompt("Column name",key)?.trim()||key;const type=window.prompt("Type: text, number, boolean, date, select, formula","text")?.trim()||"text";const formula=type==="formula"?window.prompt("Formula, e.g. ={price}*{qty}","")||null:null;try{await post(workspaceId,{action:"column",nodeId,sheetId,key,name,type,formula,validation:{},options:[],width:180});setStatus("Column added.");void load();}catch(e){setStatus(e instanceof Error?e.message:"Column failed.");}}
 async function addRow(){if(!sheet)return;const values:any={};for(const c of sheet.columns.filter((x:any)=>x.type!=="formula")){const v=window.prompt(c.name);if(v===null)continue;values[c.key]=c.type==="number"?Number(v):c.type==="boolean"?v==="true":v;}try{await post(workspaceId,{action:"row",nodeId,sheetId,values});setStatus("Row added.");void load();}catch(e){setStatus(e instanceof Error?e.message:"Row failed.");}}
 async function edit(row:any,col:any){if(col.type==="formula")return;const raw=window.prompt(col.name,String(row.values?.[col.key]??""));if(raw===null)return;const value=col.type==="number"?Number(raw):col.type==="boolean"?raw==="true":raw;try{await post(workspaceId,{action:"row",nodeId,sheetId,rowId:row.id,expectedVersion:row.version,values:{[col.key]:value}});void load();}catch(e){setStatus(e instanceof Error?e.message:"Update failed.");}}
 return <section className={styles.surface}><header className={styles.head}><div><p className="eyebrow">{doc?.kind??"structured data"}</p><h2>{doc?.name??"Structured data"}</h2><p>Typed columns, validation, safe formulas and saved views.</p></div><div className={styles.actions}><Button variant="secondary" onClick={()=>void addColumn()}>Add column</Button><Button onClick={()=>void addRow()}>Add row</Button></div></header>
 <div className={styles.toolbar}><select value={sheetId} onChange={e=>setSheetId(e.currentTarget.value)}>{doc?.sheets?.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input value={filter} onChange={e=>setFilter(e.currentTarget.value)} placeholder="Filter Name…"/><Button variant="secondary" onClick={()=>void load()}>Refresh</Button></div>
 <div className={styles.gridWrap}><table><thead><tr>{sheet?.columns?.map((c:any)=><th key={c.id} style={{minWidth:c.width}}>{c.name}<small>{c.type}{c.formula?" · "+c.formula:""}</small></th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>{sheet?.columns?.map((c:any)=><td key={c.id}><button onClick={()=>void edit(r,c)} disabled={c.type==="formula"}>{String(c.type==="formula"?r.computed?.[c.key]??"":r.values?.[c.key]??"")}</button></td>)}</tr>)}</tbody></table></div>
 <div className={styles.cards}>{rows.map(r=><article key={r.id}>{sheet?.columns?.map((c:any)=><div key={c.id}><strong>{c.name}</strong><button onClick={()=>void edit(r,c)} disabled={c.type==="formula"}>{String(c.type==="formula"?r.computed?.[c.key]??"":r.values?.[c.key]??"")}</button></div>)}</article>)}</div>
 <p className={styles.live} aria-live="polite">{status}</p></section>;
}

export function CodeDocumentEditor({workspaceId,nodeId}:{workspaceId:string;nodeId:string}){
 const[data,setData]=useState<any>(null),[source,setSource]=useState(""),[lang,setLang]=useState("text"),[status,setStatus]=useState("Loading…");
 const load=useCallback(async()=>{try{const d=await get<any>(workspaceId,"code",nodeId);setData(d);setSource(d.source);setLang(d.language);setStatus("Saved");}catch(e){setStatus(e instanceof Error?e.message:"Load failed.");}},[workspaceId,nodeId]);
 useEffect(()=>{void load();},[load]);
 async function save(){if(!data)return;setStatus("Saving…");try{const d=await post<any>(workspaceId,{action:"code",nodeId,language:lang,source,expectedVersion:data.version});setData({...data,...d});setStatus("Saved");}catch(e){setStatus(e instanceof Error?e.message:"Save failed.");}}
 return <section className={styles.surface}><header className={styles.head}><div><p className="eyebrow">Code document</p><h2>{data?.name??"Code"}</h2></div><div className={styles.actions}><select value={lang} onChange={e=>setLang(e.currentTarget.value)}><option>text</option><option>javascript</option><option>typescript</option><option>python</option><option>sql</option><option>r</option></select><Button onClick={()=>void save()}>Save</Button></div></header><textarea className={styles.code} value={source} onChange={e=>{setSource(e.currentTarget.value);setStatus("Unsaved changes");}} spellCheck={false}/><p className={styles.live}>{status}</p></section>;
}

export function ComputationalNotebookEditor({workspaceId,nodeId}:{workspaceId:string;nodeId:string}){
 const[cells,setCells]=useState<any[]>([]),[status,setStatus]=useState("Loading…");
 const load=useCallback(async()=>{try{const d=await get<any>(workspaceId,"notebook",nodeId);setCells(d.cells??[]);setStatus("");}catch(e){setStatus(e instanceof Error?e.message:"Load failed.");}},[workspaceId,nodeId]);useEffect(()=>{void load();},[load]);
 async function add(type:"markdown"|"code"){try{await post(workspaceId,{action:"cell",nodeId,type,language:type==="code"?"python":undefined,source:""});void load();}catch(e){setStatus(e instanceof Error?e.message:"Cell failed.");}}
 async function save(c:any,source:string){try{await post(workspaceId,{action:"cell",nodeId,cellId:c.id,expectedVersion:c.version,source});setStatus("Saved");void load();}catch(e){setStatus(e instanceof Error?e.message:"Save failed.");}}
 async function execute(){try{await post(workspaceId,{action:"execute",nodeId});}catch(e){setStatus(e instanceof Error?e.message:"Execution disabled.");}}
 return <section className={styles.surface}><header className={styles.head}><div><p className="eyebrow">Computational notebook</p><h2>Notebook</h2><p>Source cells are editable. Execution is disabled unless an approved isolated sandbox is deployed.</p></div><div className={styles.actions}><Button variant="secondary" onClick={()=>void add("markdown")}>Markdown cell</Button><Button variant="secondary" onClick={()=>void add("code")}>Code cell</Button><Button onClick={()=>void execute()}>Run</Button></div></header><div className={styles.cells}>{cells.map(c=><NotebookCell key={c.id} cell={c} onSave={s=>void save(c,s)}/>)}</div><p className={styles.live}>{status}</p></section>;
}
function NotebookCell({cell,onSave}:{cell:any;onSave:(s:string)=>void}){const[v,setV]=useState(cell.source);return <article className={styles.cell}><header><strong>{cell.type}{cell.language?" · "+cell.language:""}</strong><Button variant="secondary" onClick={()=>onSave(v)}>Save</Button></header><textarea value={v} onChange={e=>setV(e.currentTarget.value)} spellCheck={cell.type==="markdown"}/>{cell.outputs?.length?<div className={styles.outputs}>{cell.outputs.map((o:any)=><pre key={o.id}>{JSON.stringify(o.content,null,2)}</pre>)}</div>:null}</article>;}
