import type{AuthVerifier}from"@nexosophy/auth";
import{createAssignmentSchema,createCardSchema,createCourseSchema,createDeckSchema,createExamSchema,createTermSchema,linkCourseNodeSchema,reviewCardSchema}from"@nexosophy/contracts";
import{academicDashboard,addCourseSection,addGradeItem,archiveAcademicTerm,courseDetail,createAcademicCourse,createAcademicTerm,createAssignment,createCourseMeeting,createExam,createFlashcard,createFlashcardDeck,createStudyPlan,linkCourseNode,linkStudyFocusSession,listDueFlashcards,reviewFlashcard}from"@nexosophy/db";
import type{FastifyInstance}from"fastify";
import{authorizeWorkspace,type DatabasePool,denyWorkspaceAuth,requireWorkspacePrincipal,sendWorkspaceError}from"./workspace-route-common.js";
function fail(reply:any,request:any,e:unknown,status=400){const code=e instanceof Error?e.message:"ACADEMIC_ERROR";return sendWorkspaceError(reply,request.id,status,code,code.toLowerCase().replaceAll("_"," ").replace(/^./,(x:string)=>x.toUpperCase())+".");}
export async function registerAcademicRoutes(app:FastifyInstance,pool:DatabasePool,verifier:AuthVerifier=denyWorkspaceAuth){
 app.get("/v1/workspaces/:workspaceId/academic",async(request,reply)=>{const{workspaceId}=request.params as any,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.read",request,reply)))return;return academicDashboard(pool,workspaceId);});
 app.get("/v1/workspaces/:workspaceId/academic/courses/:courseId",async(request,reply)=>{const{workspaceId,courseId}=request.params as any,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.read",request,reply)))return;try{return await courseDetail(pool,workspaceId,courseId);}catch(e){return fail(reply,request,e,404);}});
 app.post("/v1/workspaces/:workspaceId/academic/terms",async(request,reply)=>{const{workspaceId}=request.params as any,b=createTermSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.create",request,reply)))return;reply.code(201);return createAcademicTerm(pool,{workspaceId,userId:p.internalUserId,...b,requestId:request.id});});
 app.post("/v1/workspaces/:workspaceId/academic/terms/:termId/archive",async(request,reply)=>{const{workspaceId,termId}=request.params as any,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.update",request,reply)))return;await archiveAcademicTerm(pool,workspaceId,p.internalUserId,termId);reply.code(204);});
 app.post("/v1/workspaces/:workspaceId/academic/courses",async(request,reply)=>{const{workspaceId}=request.params as any,b=createCourseSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.create",request,reply)))return;try{const x=await createAcademicCourse(pool,{workspaceId,userId:p.internalUserId,...b,requestId:request.id});reply.code(201);return x;}catch(e){return fail(reply,request,e);}});
 app.post("/v1/workspaces/:workspaceId/academic/courses/:courseId/sections",async(request,reply)=>{const{workspaceId,courseId}=request.params as any,b=request.body as any,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.update",request,reply)))return;if(!["lecture","lab","tutorial","seminar","other"].includes(String(b?.kind)))return fail(reply,request,new Error("SECTION_KIND_INVALID"));reply.code(201);return addCourseSection(pool,courseId,b.kind,String(b?.name??"Section").slice(0,160),b?.metadata??{});});
 app.post("/v1/workspaces/:workspaceId/academic/courses/:courseId/links",async(request,reply)=>{const{workspaceId,courseId}=request.params as any,b=linkCourseNodeSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.update",request,reply)))return;await linkCourseNode(pool,{workspaceId,courseId,...b});reply.code(204);});
 app.post("/v1/workspaces/:workspaceId/academic/courses/:courseId/meetings",async(request,reply)=>{const{workspaceId,courseId}=request.params as any,b=request.body as any,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.create",request,reply)))return;try{const x=await createCourseMeeting(pool,{workspaceId,userId:p.internalUserId,courseId,sectionId:typeof b?.sectionId==="string"?b.sectionId:undefined,title:String(b?.title??"Course meeting").slice(0,500),startsAt:new Date(String(b?.startsAt)),endsAt:new Date(String(b?.endsAt)),timezone:String(b?.timezone??"UTC")});reply.code(201);return x;}catch(e){return fail(reply,request,e);}});
 app.post("/v1/workspaces/:workspaceId/academic/assignments",async(request,reply)=>{const{workspaceId}=request.params as any,b=createAssignmentSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.create",request,reply)))return;try{const x=await createAssignment(pool,{workspaceId,userId:p.internalUserId,courseId:b.courseId,title:b.title,description:b.description,dueAt:b.dueAt?new Date(b.dueAt):undefined,timezone:b.timezone,priority:b.priority,weight:b.weight,pointsPossible:b.pointsPossible,rubric:b.rubric});reply.code(201);return x;}catch(e){return fail(reply,request,e);}});
 app.post("/v1/workspaces/:workspaceId/academic/exams",async(request,reply)=>{const{workspaceId}=request.params as any,b=createExamSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.create",request,reply)))return;try{const x=await createExam(pool,{workspaceId,userId:p.internalUserId,courseId:b.courseId,title:b.title,startsAt:new Date(b.startsAt),endsAt:new Date(b.endsAt),timezone:b.timezone,format:b.format,weight:b.weight,topics:b.topics,createRevisionTask:b.createRevisionTask});reply.code(201);return x;}catch(e){return fail(reply,request,e);}});
 app.post("/v1/workspaces/:workspaceId/academic/grades",async(request,reply)=>{const{workspaceId}=request.params as any,b=request.body as any,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.update",request,reply)))return;reply.code(201);return addGradeItem(pool,{courseId:String(b?.courseId??""),name:String(b?.name??"Grade").slice(0,160),weight:typeof b?.weight==="number"?b.weight:undefined,score:typeof b?.score==="number"?b.score:undefined,maxScore:typeof b?.maxScore==="number"?b.maxScore:undefined,metadata:b?.metadata??{}});});
 app.post("/v1/workspaces/:workspaceId/academic/study-plans",async(request,reply)=>{const{workspaceId}=request.params as any,b=request.body as any,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.create",request,reply)))return;reply.code(201);return createStudyPlan(pool,{workspaceId,userId:p.internalUserId,courseId:b?.courseId,examId:b?.examId,title:String(b?.title??"Study plan").slice(0,200),startsOn:b?.startsOn,endsOn:b?.endsOn,topics:Array.isArray(b?.topics)?b.topics:[]});});
 app.post("/v1/workspaces/:workspaceId/academic/study-sessions",async(request,reply)=>{const{workspaceId}=request.params as any,b=request.body as any,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.update",request,reply)))return;await linkStudyFocusSession(pool,{workspaceId,planId:b?.planId,courseId:b?.courseId,focusSessionId:String(b?.focusSessionId??"")});reply.code(204);});
 app.get("/v1/workspaces/:workspaceId/academic/flashcards/due",async(request,reply)=>{const{workspaceId}=request.params as any,deckId=(request.query as any)?.deckId,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.read",request,reply)))return;return{items:await listDueFlashcards(pool,workspaceId,typeof deckId==="string"?deckId:undefined)};});
 app.post("/v1/workspaces/:workspaceId/academic/flashcards/decks",async(request,reply)=>{const{workspaceId}=request.params as any,b=createDeckSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.create",request,reply)))return;reply.code(201);return createFlashcardDeck(pool,{workspaceId,userId:p.internalUserId,...b});});
 app.post("/v1/workspaces/:workspaceId/academic/flashcards/cards",async(request,reply)=>{const{workspaceId}=request.params as any,b=createCardSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.create",request,reply)))return;reply.code(201);return createFlashcard(pool,{workspaceId,...b});});
 app.post("/v1/workspaces/:workspaceId/academic/flashcards/:cardId/review",async(request,reply)=>{const{workspaceId,cardId}=request.params as any,b=reviewCardSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.update",request,reply)))return;try{return await reviewFlashcard(pool,{workspaceId,userId:p.internalUserId,cardId,grade:b.grade});}catch(e){return fail(reply,request,e,404);}});
}
