import type{AuthVerifier}from"@nexosophy/auth";
import{analysisDatasetSchema,analysisRecipeSchema,analysisRunSchema,analysisVisualizationSchema,analysisDashboardSchema,analysisExportSchema}from"@nexosophy/contracts";
import{analysisDashboardDetail,analysisHome,createAnalysisDashboard,createAnalysisDataset,createAnalysisRecipe,createVisualization,datasetSummary,linkAnalysisNotebook,queueAnalysisExport,runAnalysisRecipe,visualizationData}from"@nexosophy/db";
import type{StorageAdapter}from"@nexosophy/storage";import type{FastifyInstance}from"fastify";import{authorizeWorkspace,type DatabasePool,denyWorkspaceAuth,requireWorkspacePrincipal,sendWorkspaceError}from"./workspace-route-common.js";
function fail(reply:any,r:any,e:unknown,status=400){const code=e instanceof Error?e.message:"ANALYSIS_ERROR";return sendWorkspaceError(reply,r.id,code.includes("NOT_FOUND")?404:/NOT_READY/.test(code)?409:status,code,code.toLowerCase().replaceAll("_"," ")+".")}
export async function registerAnalysisRoutes(app:FastifyInstance,pool:DatabasePool,storage:StorageAdapter|null,verifier:AuthVerifier=denyWorkspaceAuth){const p=async(r:any,reply:any,w:string,perm:string)=>{const x=await requireWorkspacePrincipal(r,reply,verifier);if(!x)return null;if(!(await authorizeWorkspace(pool,x,w,perm as any,r,reply)))return null;return x};
app.get("/v1/workspaces/:workspaceId/analysis",async(r,reply)=>{const{workspaceId}=r.params as any,x=await p(r,reply,workspaceId,"content.read");if(!x)return;return analysisHome(pool,workspaceId)});
app.post("/v1/workspaces/:workspaceId/analysis/datasets",async(r,reply)=>{const{workspaceId}=r.params as any,b=analysisDatasetSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.create");if(!x)return;try{reply.code(202);return await createAnalysisDataset(pool,{workspaceId,userId:x.internalUserId,...b})}catch(e){return fail(reply,r,e)}});
app.get("/v1/workspaces/:workspaceId/analysis/datasets/:datasetId/summary",async(r,reply)=>{const{workspaceId,datasetId}=r.params as any,x=await p(r,reply,workspaceId,"content.read");if(!x)return;try{return await datasetSummary(pool,workspaceId,datasetId)}catch(e){return fail(reply,r,e,404)}});
app.post("/v1/workspaces/:workspaceId/analysis/recipes",async(r,reply)=>{const{workspaceId}=r.params as any,b=analysisRecipeSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.create");if(!x)return;reply.code(201);return createAnalysisRecipe(pool,{workspaceId,userId:x.internalUserId,...b})});
app.post("/v1/workspaces/:workspaceId/analysis/runs",async(r,reply)=>{const{workspaceId}=r.params as any,b=analysisRunSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.create");if(!x)return;try{reply.code(202);return await runAnalysisRecipe(pool,{workspaceId,userId:x.internalUserId,...b})}catch(e){return fail(reply,r,e)}});
app.post("/v1/workspaces/:workspaceId/analysis/visualizations",async(r,reply)=>{const{workspaceId}=r.params as any,b=analysisVisualizationSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.create");if(!x)return;try{reply.code(201);return await createVisualization(pool,{workspaceId,userId:x.internalUserId,...b})}catch(e){return fail(reply,r,e)}});
app.get("/v1/workspaces/:workspaceId/analysis/visualizations/:visualizationId/data",async(r,reply)=>{const{workspaceId,visualizationId}=r.params as any,x=await p(r,reply,workspaceId,"content.read");if(!x)return;try{return await visualizationData(pool,workspaceId,visualizationId)}catch(e){return fail(reply,r,e,404)}});
app.post("/v1/workspaces/:workspaceId/analysis/dashboards",async(r,reply)=>{const{workspaceId}=r.params as any,b=analysisDashboardSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.create");if(!x)return;reply.code(201);return createAnalysisDashboard(pool,{workspaceId,userId:x.internalUserId,...b})});
app.get("/v1/workspaces/:workspaceId/analysis/dashboards/:dashboardId",async(r,reply)=>{const{workspaceId,dashboardId}=r.params as any,x=await p(r,reply,workspaceId,"content.read");if(!x)return;try{const d=await analysisDashboardDetail(pool,workspaceId,dashboardId),widgets=[];for(const w of d.widgets)widgets.push({...w,data:await visualizationData(pool,workspaceId,w.visualization_id)});return{...d,widgets}}catch(e){return fail(reply,r,e,404)}});
app.post("/v1/workspaces/:workspaceId/analysis/notebook-links",async(r,reply)=>{const{workspaceId}=r.params as any,b=r.body as any,x=await p(r,reply,workspaceId,"content.update");if(!x)return;try{await linkAnalysisNotebook(pool,{workspaceId,userId:x.internalUserId,datasetId:String(b.datasetId),nodeId:String(b.nodeId)});reply.code(204);return}catch(e){return fail(reply,r,e)}});
app.post("/v1/workspaces/:workspaceId/analysis/exports",async(r,reply)=>{const{workspaceId}=r.params as any,b=analysisExportSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.read");if(!x)return;reply.code(202);return queueAnalysisExport(pool,{workspaceId,userId:x.internalUserId,...b})});
app.get("/v1/workspaces/:workspaceId/analysis/exports/:exportId/download",async(r,reply)=>{if(!storage)return fail(reply,r,new Error("STORAGE_UNAVAILABLE"),503);const{workspaceId,exportId}=r.params as any,x=await p(r,reply,workspaceId,"content.read");if(!x)return;const e=(await pool.query<any>(`select * from "analysis_exports" where "workspace_id"=$1 and "id"=$2 and "status"='succeeded'`,[workspaceId,exportId])).rows[0];if(!e?.artifact_object_key)return fail(reply,r,new Error("ANALYSIS_EXPORT_NOT_READY"),409);const u=await storage.createDownloadUrl({key:e.artifact_object_key,expiresInSeconds:600});return{url:u.url,filename:e.artifact_filename,mimeType:e.artifact_mime}})
}