import type{AuthVerifier}from"@nexosophy/auth";import{offlinePolicySchema,offlineSyncSchema,offlineConflictResolutionSchema,offlinePinSchema}from"@nexosophy/contracts";import{applyOfflineMutation,getOfflinePolicy,listOfflineConflicts,listOfflineDevices,listOfflinePins,registerOfflineDevice,resolveOfflineConflict,revokeOfflineDevice,setOfflinePin,updateOfflinePolicy}from"@nexosophy/db";import type{FastifyInstance}from"fastify";import{authorizeWorkspace,type DatabasePool,denyWorkspaceAuth,requireWorkspacePrincipal,sendWorkspaceError}from"./workspace-route-common.js";
function fail(reply:any,r:any,e:unknown,status=400){const code=e instanceof Error?e.message:"OFFLINE_ERROR";return sendWorkspaceError(reply,r.id,/DISABLED|REVOKED|UNREGISTERED/.test(code)?403:/CONFLICT|QUOTA/.test(code)?409:code.includes("NOT_FOUND")?404:status,code,code.toLowerCase().replaceAll("_"," ")+".")}
export async function registerOfflineRoutes(app:FastifyInstance,pool:DatabasePool,verifier:AuthVerifier=denyWorkspaceAuth){const p=async(r:any,reply:any,w:string,perm:string)=>{const x=await requireWorkspacePrincipal(r,reply,verifier);if(!x)return null;if(!(await authorizeWorkspace(pool,x,w,perm as any,r,reply)))return null;return x};
app.get("/v1/workspaces/:workspaceId/offline",async(r,reply)=>{const{workspaceId}=r.params as any,q=r.query as any,x=await p(r,reply,workspaceId,"content.read");if(!x)return;const[policy,devices,conflicts,pins]=await Promise.all([getOfflinePolicy(pool,workspaceId),listOfflineDevices(pool,workspaceId,x.internalUserId),listOfflineConflicts(pool,workspaceId,x.internalUserId),listOfflinePins(pool,workspaceId,x.internalUserId,typeof q.deviceId==="string"?q.deviceId:undefined)]);return{policy,devices,conflicts,pins}});
app.put("/v1/workspaces/:workspaceId/offline/policy",async(r,reply)=>{const{workspaceId}=r.params as any,b=offlinePolicySchema.parse(r.body),x=await p(r,reply,workspaceId,"workspace.update");if(!x)return;return updateOfflinePolicy(pool,{workspaceId,userId:x.internalUserId,...b})});
app.post("/v1/workspaces/:workspaceId/offline/sync",async(r,reply)=>{const{workspaceId}=r.params as any,b=offlineSyncSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.update");if(!x)return;try{const device=await registerOfflineDevice(pool,{workspaceId,userId:x.internalUserId,...b.device}),results=[];for(const op of b.operations){results.push(await applyOfflineMutation(pool,{workspaceId,userId:x.internalUserId,...op}))}return{device:{deviceId:device.device_id,lastSeenAt:device.last_seen_at},results,conflicts:await listOfflineConflicts(pool,workspaceId,x.internalUserId)}}catch(e){return fail(reply,r,e)}});
app.post("/v1/workspaces/:workspaceId/offline/conflicts/:conflictId/resolve",async(r,reply)=>{const{workspaceId,conflictId}=r.params as any,b=offlineConflictResolutionSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.update");if(!x)return;try{return await resolveOfflineConflict(pool,{workspaceId,userId:x.internalUserId,conflictId,...b})}catch(e){return fail(reply,r,e)}});
app.post("/v1/workspaces/:workspaceId/offline/pins",async(r,reply)=>{const{workspaceId}=r.params as any,b=offlinePinSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.read");if(!x)return;try{await registerOfflineDevice(pool,{workspaceId,userId:x.internalUserId,deviceId:b.deviceId,label:"Browser",platform:r.headers["user-agent"]??"",appVersion:"web",reportedBytes:0});await setOfflinePin(pool,{workspaceId,userId:x.internalUserId,...b});reply.code(204);return}catch(e){return fail(reply,r,e)}});
app.delete("/v1/workspaces/:workspaceId/offline/devices/:deviceId",async(r,reply)=>{const{workspaceId,deviceId}=r.params as any,x=await p(r,reply,workspaceId,"content.update");if(!x)return;try{await revokeOfflineDevice(pool,{workspaceId,userId:x.internalUserId,deviceId});reply.code(204);return}catch(e){return fail(reply,r,e,404)}})}
