import type{AuthVerifier}from"@nexosophy/auth";
import{investigationSchema,leadSchema,sourceSchema,interviewSchema,evidenceSchema,claimSchema,claimReviewSchema,claimEvidenceSchema,timelineEventSchema,reportSchema,reportReviewSchema,reportStatusSchema,redactionSchema}from"@nexosophy/contracts";
import{createInvestigation,createLead,createSource,grantSourceAccess,createInterview,createEvidence,createClaim,reviewClaim,linkClaimEvidence,addTimelineEvent,addInvestigationTask,createReport,upsertReportReview,updateReportStatus,addReportRedaction,reportingDashboard,investigationDetail,reportDetail,exportPublication}from"@nexosophy/db";
import type{FastifyInstance}from"fastify";import{authorizeWorkspace,type DatabasePool,denyWorkspaceAuth,requireWorkspacePrincipal,sendWorkspaceError}from"./workspace-route-common.js";
function fail(reply:any,request:any,e:unknown,status=400){const code=e instanceof Error?e.message:"REPORTING_ERROR";return sendWorkspaceError(reply,request.id,/DENIED/.test(code)?403:/CONFLICT|INVALID_TRANSITION|MUST_BE/.test(code)?409:code.includes("NOT_FOUND")?404:status,code,code.toLowerCase().replaceAll("_"," ")+".")}
export async function registerReportingRoutes(app:FastifyInstance,pool:DatabasePool,verifier:AuthVerifier=denyWorkspaceAuth){const p=async(r:any,reply:any,w:string,perm:string)=>{const x=await requireWorkspacePrincipal(r,reply,verifier);if(!x)return null;if(!(await authorizeWorkspace(pool,x,w,perm as any,r,reply)))return null;return x};
app.get("/v1/workspaces/:workspaceId/reporting",async(r,reply)=>{const{workspaceId}=r.params as any,x=await p(r,reply,workspaceId,"content.read");if(!x)return;return reportingDashboard(pool,workspaceId,x.internalUserId)});
app.get("/v1/workspaces/:workspaceId/reporting/investigations/:investigationId",async(r,reply)=>{const{workspaceId,investigationId}=r.params as any,x=await p(r,reply,workspaceId,"content.read");if(!x)return;try{return await investigationDetail(pool,workspaceId,investigationId,x.internalUserId)}catch(e){return fail(reply,r,e,404)}});
app.post("/v1/workspaces/:workspaceId/reporting/investigations",async(r,reply)=>{const{workspaceId}=r.params as any,b=investigationSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.create");if(!x)return;reply.code(201);return createInvestigation(pool,{workspaceId,userId:x.internalUserId,title:b.title,summary:b.summary,classification:b.classification,embargoUntil:b.embargoUntil?new Date(b.embargoUntil):undefined,requestId:r.id})});
app.post("/v1/workspaces/:workspaceId/reporting/leads",async(r,reply)=>{const{workspaceId}=r.params as any,b=leadSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.create");if(!x)return;reply.code(201);return createLead(pool,{workspaceId,userId:x.internalUserId,...b})});
app.post("/v1/workspaces/:workspaceId/reporting/sources",async(r,reply)=>{const{workspaceId}=r.params as any,b=sourceSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.create");if(!x)return;reply.code(201);return createSource(pool,{workspaceId,userId:x.internalUserId,...b})});
app.post("/v1/workspaces/:workspaceId/reporting/sources/:sourceId/grants",async(r,reply)=>{const{workspaceId,sourceId}=r.params as any,b=r.body as any,x=await p(r,reply,workspaceId,"workspace.update");if(!x)return;try{await grantSourceAccess(pool,{workspaceId,sourceId,actorUserId:x.internalUserId,userId:String(b.userId??"")});reply.code(204);return}catch(e){return fail(reply,r,e)}});
app.post("/v1/workspaces/:workspaceId/reporting/interviews",async(r,reply)=>{const{workspaceId}=r.params as any,b=interviewSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.create");if(!x)return;try{reply.code(201);return await createInterview(pool,{workspaceId,userId:x.internalUserId,investigationId:b.investigationId,sourceId:b.sourceId,title:b.title,occurredAt:b.occurredAt?new Date(b.occurredAt):undefined,audioAssetId:b.audioAssetId,consent:b.consent})}catch(e){return fail(reply,r,e)}});
app.post("/v1/workspaces/:workspaceId/reporting/evidence",async(r,reply)=>{const{workspaceId}=r.params as any,b=evidenceSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.create");if(!x)return;try{reply.code(201);return await createEvidence(pool,{workspaceId,userId:x.internalUserId,...b})}catch(e){return fail(reply,r,e)}});
app.post("/v1/workspaces/:workspaceId/reporting/claims",async(r,reply)=>{const{workspaceId}=r.params as any,b=claimSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.create");if(!x)return;reply.code(201);return createClaim(pool,{workspaceId,userId:x.internalUserId,...b})});
app.patch("/v1/workspaces/:workspaceId/reporting/claims/:claimId",async(r,reply)=>{const{workspaceId,claimId}=r.params as any,b=claimReviewSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.update");if(!x)return;try{return await reviewClaim(pool,{workspaceId,claimId,userId:x.internalUserId,...b})}catch(e){return fail(reply,r,e)}});
app.post("/v1/workspaces/:workspaceId/reporting/claims/:claimId/evidence",async(r,reply)=>{const{workspaceId,claimId}=r.params as any,b=claimEvidenceSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.update");if(!x)return;await linkClaimEvidence(pool,{workspaceId,claimId,userId:x.internalUserId,...b});reply.code(204)});
app.post("/v1/workspaces/:workspaceId/reporting/timeline",async(r,reply)=>{const{workspaceId}=r.params as any,b=timelineEventSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.create");if(!x)return;reply.code(201);return addTimelineEvent(pool,{workspaceId,userId:x.internalUserId,investigationId:b.investigationId,occurredAt:new Date(b.occurredAt),title:b.title,description:b.description,evidenceId:b.evidenceId,sourceId:b.sourceId})});
app.post("/v1/workspaces/:workspaceId/reporting/investigations/:investigationId/tasks",async(r,reply)=>{const{workspaceId,investigationId}=r.params as any,b=r.body as any,x=await p(r,reply,workspaceId,"content.create");if(!x)return;reply.code(201);return addInvestigationTask(pool,{workspaceId,userId:x.internalUserId,investigationId,title:String(b.title??"Reporting task"),dueAt:b.dueAt?new Date(b.dueAt):undefined})});
app.post("/v1/workspaces/:workspaceId/reports",async(r,reply)=>{const{workspaceId}=r.params as any,b=reportSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.create");if(!x)return;reply.code(201);return createReport(pool,{workspaceId,userId:x.internalUserId,...b})});
app.get("/v1/workspaces/:workspaceId/reports/:reportId",async(r,reply)=>{const{workspaceId,reportId}=r.params as any,x=await p(r,reply,workspaceId,"content.read");if(!x)return;try{return await reportDetail(pool,workspaceId,reportId)}catch(e){return fail(reply,r,e,404)}});
app.post("/v1/workspaces/:workspaceId/reports/:reportId/reviews",async(r,reply)=>{const{workspaceId,reportId}=r.params as any,b=reportReviewSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.update");if(!x)return;reply.code(201);return upsertReportReview(pool,{workspaceId,reportId,userId:x.internalUserId,...b})});
app.patch("/v1/workspaces/:workspaceId/reports/:reportId/status",async(r,reply)=>{const{workspaceId,reportId}=r.params as any,b=reportStatusSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.update");if(!x)return;try{return await updateReportStatus(pool,{workspaceId,reportId,userId:x.internalUserId,...b})}catch(e){return fail(reply,r,e)}});
app.post("/v1/workspaces/:workspaceId/reports/:reportId/redactions",async(r,reply)=>{const{workspaceId,reportId}=r.params as any,b=redactionSchema.parse(r.body),x=await p(r,reply,workspaceId,"content.update");if(!x)return;reply.code(201);return addReportRedaction(pool,{workspaceId,reportId,userId:x.internalUserId,...b})});
app.get("/v1/workspaces/:workspaceId/reports/:reportId/export",async(r,reply)=>{const{workspaceId,reportId}=r.params as any,q=r.query as any,x=await p(r,reply,workspaceId,"content.read");if(!x)return;try{return await exportPublication(pool,{workspaceId,reportId,userId:x.internalUserId,redacted:q.redacted!=="false"})}catch(e){return fail(reply,r,e,404)}})}
