import type { AuthVerifier } from "@nexosophy/auth";
import {
  createNotebookCellSchema,createSpecializedNodeSchema,createStructuredColumnSchema,
  createStructuredViewSchema,reorderNotebookCellsSchema,structuredRowsQuerySchema,
  updateCodeDocumentSchema,updateNotebookCellSchema,upsertStructuredRowSchema,
} from "@nexosophy/contracts";
import {
  clearNotebookOutputs,createNotebookCell,createSpecializedNode,createStructuredChart,
  createStructuredColumn,createStructuredView,getCodeDocument,getExecutionPolicy,
  getNotebook,getStructuredDocument,listSpecializedHistory,listStructuredRows,
  reorderNotebookCells,updateCodeDocument,updateNotebookCell,upsertStructuredRow,
} from "@nexosophy/db";
import type { FastifyInstance } from "fastify";
import {authorizeWorkspace,type DatabasePool,denyWorkspaceAuth,requireWorkspacePrincipal,sendWorkspaceError} from "./workspace-route-common.js";

function fail(reply:any,request:any,e:unknown,status=400){const code=e instanceof Error?e.message:"STRUCTURED_ERROR";return sendWorkspaceError(reply,request.id,status,code,code.toLowerCase().replaceAll("_"," ").replace(/^./,(x:string)=>x.toUpperCase())+".");}
export async function registerStructuredCodeRoutes(app:FastifyInstance,pool:DatabasePool,verifier:AuthVerifier=denyWorkspaceAuth){
 app.post("/v1/workspaces/:workspaceId/specialized",async(request,reply)=>{const{workspaceId}=request.params as any,b=createSpecializedNodeSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.create",request,reply)))return;try{const x=await createSpecializedNode(pool,{workspaceId,actorUserId:p.internalUserId,parentId:b.parentId,kind:b.kind,name:b.name,language:b.language,requestId:request.id});reply.code(201);return x;}catch(e){return fail(reply,request,e);}});
 app.get("/v1/workspaces/:workspaceId/structured/:nodeId",async(request,reply)=>{const{workspaceId,nodeId}=request.params as any,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.read",request,reply)))return;try{return await getStructuredDocument(pool,workspaceId,nodeId);}catch(e){return fail(reply,request,e,404);}});
 app.get("/v1/workspaces/:workspaceId/structured/:nodeId/rows",async(request,reply)=>{const{workspaceId,nodeId}=request.params as any,q=structuredRowsQuerySchema.parse(request.query),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.read",request,reply)))return;try{return await listStructuredRows(pool,{workspaceId,nodeId,sheetId:q.sheetId,cursor:q.cursor,limit:q.limit,sortKey:q.sortKey,sortDir:q.sortDir,filterKey:q.filterKey,filterValue:q.filterValue});}catch(e){return fail(reply,request,e);}});
 app.post("/v1/workspaces/:workspaceId/structured/:nodeId/columns",async(request,reply)=>{const{workspaceId,nodeId}=request.params as any,b=createStructuredColumnSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.update",request,reply)))return;try{const x=await createStructuredColumn(pool,{workspaceId,nodeId,actorUserId:p.internalUserId,...b});reply.code(201);return x;}catch(e){return fail(reply,request,e);}});
 app.post("/v1/workspaces/:workspaceId/structured/:nodeId/rows",async(request,reply)=>{const{workspaceId,nodeId}=request.params as any,b=upsertStructuredRowSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.update",request,reply)))return;try{return await upsertStructuredRow(pool,{workspaceId,nodeId,actorUserId:p.internalUserId,sheetId:b.sheetId,rowId:b.rowId,expectedVersion:b.expectedVersion,values:b.values});}catch(e){return fail(reply,request,e,e instanceof Error&&e.message==="ROW_VERSION_CONFLICT"?409:400);}});
 app.post("/v1/workspaces/:workspaceId/structured/:nodeId/views",async(request,reply)=>{const{workspaceId,nodeId}=request.params as any,b=createStructuredViewSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.update",request,reply)))return;const d=await getStructuredDocument(pool,workspaceId,nodeId);reply.code(201);return createStructuredView(pool,{workspaceId,nodeId,documentId:d.id,actorUserId:p.internalUserId,name:b.name,type:b.type,config:b.config});});
 app.post("/v1/workspaces/:workspaceId/structured/:nodeId/charts",async(request,reply)=>{const{workspaceId,nodeId}=request.params as any,b=request.body as any,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.update",request,reply)))return;if(!["bar","line","pie"].includes(String(b?.type)))return fail(reply,request,new Error("CHART_TYPE_INVALID"));const d=await getStructuredDocument(pool,workspaceId,nodeId);reply.code(201);return createStructuredChart(pool,{workspaceId,nodeId,documentId:d.id,actorUserId:p.internalUserId,name:String(b?.name??"Chart").slice(0,120),type:b.type,config:typeof b?.config==="object"&&b.config?b.config:{}});});
 app.get("/v1/workspaces/:workspaceId/code/:nodeId",async(request,reply)=>{const{workspaceId,nodeId}=request.params as any,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.read",request,reply)))return;try{return await getCodeDocument(pool,workspaceId,nodeId);}catch(e){return fail(reply,request,e,404);}});
 app.put("/v1/workspaces/:workspaceId/code/:nodeId",async(request,reply)=>{const{workspaceId,nodeId}=request.params as any,b=updateCodeDocumentSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.update",request,reply)))return;try{return await updateCodeDocument(pool,{workspaceId,nodeId,actorUserId:p.internalUserId,...b});}catch(e){return fail(reply,request,e,e instanceof Error&&e.message==="CODE_VERSION_CONFLICT"?409:400);}});
 app.get("/v1/workspaces/:workspaceId/notebooks/:nodeId",async(request,reply)=>{const{workspaceId,nodeId}=request.params as any,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.read",request,reply)))return;return getNotebook(pool,workspaceId,nodeId);});
 app.post("/v1/workspaces/:workspaceId/notebooks/:nodeId/cells",async(request,reply)=>{const{workspaceId,nodeId}=request.params as any,b=createNotebookCellSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.update",request,reply)))return;reply.code(201);return createNotebookCell(pool,{workspaceId,nodeId,actorUserId:p.internalUserId,...b});});
 app.patch("/v1/workspaces/:workspaceId/notebooks/:nodeId/cells/:cellId",async(request,reply)=>{const{workspaceId,nodeId,cellId}=request.params as any,b=updateNotebookCellSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.update",request,reply)))return;try{return await updateNotebookCell(pool,{workspaceId,nodeId,cellId,actorUserId:p.internalUserId,expectedVersion:b.expectedVersion,type:b.type,language:b.language,source:b.source});}catch(e){return fail(reply,request,e,e instanceof Error&&e.message==="NOTEBOOK_CELL_VERSION_CONFLICT"?409:400);}});
 app.post("/v1/workspaces/:workspaceId/notebooks/:nodeId/reorder",async(request,reply)=>{const{workspaceId,nodeId}=request.params as any,b=reorderNotebookCellsSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.update",request,reply)))return;await reorderNotebookCells(pool,{workspaceId,nodeId,cellIds:b.cellIds,actorUserId:p.internalUserId});reply.code(204);});
 app.delete("/v1/workspaces/:workspaceId/notebooks/:nodeId/outputs",async(request,reply)=>{const{workspaceId,nodeId}=request.params as any,cellId=(request.query as any)?.cellId as string|undefined,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.update",request,reply)))return;await clearNotebookOutputs(pool,{workspaceId,nodeId,cellId,actorUserId:p.internalUserId});reply.code(204);});
 app.post("/v1/workspaces/:workspaceId/notebooks/:nodeId/execute",async(request,reply)=>{const{workspaceId}=request.params as any,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.update",request,reply)))return;const policy=await getExecutionPolicy(pool,workspaceId);reply.code(403);return{error:{code:"EXECUTION_DISABLED",message:policy.enabled?"No approved sandbox runtime is configured.":"Code execution is disabled by workspace policy.",requestId:request.id}};});
 app.get("/v1/workspaces/:workspaceId/specialized/:nodeId/history",async(request,reply)=>{const{workspaceId,nodeId}=request.params as any,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.read",request,reply)))return;return{items:await listSpecializedHistory(pool,workspaceId,nodeId)};});
}
