import { omitUndefined } from "./omit-undefined.js";
import type{AuthVerifier}from"@nexosophy/auth";
import{teachingCourseSchema,teachingMemberSchema,teachingResourceSchema,teachingFeedbackSchema,supervisionSchema,supervisionMilestoneSchema,supervisionMeetingSchema,officeHourSchema,officeHourBookingSchema}from"@nexosophy/contracts";
import{enableTeachingCourse,setTeachingMember,distributeTeachingResource,upsertTeachingFeedback,createSupervision,createSupervisionMilestone,createSupervisionMeeting,createOfficeHour,bookOfficeHour,teachingHome,teachingCourseDetail,supervisionDetail}from"@nexosophy/db";
import type{FastifyInstance}from"fastify";
import{authorizeWorkspace,type DatabasePool,denyWorkspaceAuth,requireWorkspacePrincipal,sendWorkspaceError}from"./workspace-route-common.js";
function fail(reply:any,request:any,e:unknown,status=400){const code=e instanceof Error?e.message:"TEACHING_ERROR";return sendWorkspaceError(reply,request.id,/DENIED|REQUIRED|REVOKED/.test(code)?403:/CONFLICT|FULL/.test(code)?409:status,code,code.toLowerCase().replaceAll("_"," ")+".")}
export async function registerTeachingRoutes(app:FastifyInstance,pool:DatabasePool,verifier:AuthVerifier=denyWorkspaceAuth){
 const principal=async(r:any,reply:any,w:string,perm:string)=>{const x=await requireWorkspacePrincipal(r,reply,verifier);if(!x)return null;if(!(await authorizeWorkspace(pool,x,w,perm as any,r,reply)))return null;return x};
 app.get("/v1/workspaces/:workspaceId/teach",async(r,reply)=>{const{workspaceId}=r.params as any,x=await principal(r,reply,workspaceId,"content.read");if(!x)return;return teachingHome(pool,workspaceId,x.internalUserId)});
 app.post("/v1/workspaces/:workspaceId/teach/courses",async(r,reply)=>{const{workspaceId}=r.params as any,b=teachingCourseSchema.parse(r.body),x=await principal(r,reply,workspaceId,"content.update");if(!x)return;try{reply.code(201);return await enableTeachingCourse(pool,{workspaceId,courseId:b.courseId,userId:x.internalUserId})}catch(e){return fail(reply,r,e)}});
 app.get("/v1/workspaces/:workspaceId/teach/courses/:courseId",async(r,reply)=>{const{workspaceId,courseId}=r.params as any,x=await principal(r,reply,workspaceId,"content.read");if(!x)return;try{return await teachingCourseDetail(pool,workspaceId,courseId,x.internalUserId)}catch(e){return fail(reply,r,e,404)}});
 app.post("/v1/workspaces/:workspaceId/teach/courses/:courseId/members",async(r,reply)=>{const{workspaceId,courseId}=r.params as any,b=teachingMemberSchema.parse(r.body),x=await principal(r,reply,workspaceId,"content.update");if(!x)return;try{await setTeachingMember(pool,{workspaceId,courseId,actorUserId:x.internalUserId,userId:b.userId,role:b.role,active:true});reply.code(204);return}catch(e){return fail(reply,r,e)}});
 app.delete("/v1/workspaces/:workspaceId/teach/courses/:courseId/members/:userId",async(r,reply)=>{const{workspaceId,courseId,userId}=r.params as any,x=await principal(r,reply,workspaceId,"content.update");if(!x)return;try{await setTeachingMember(pool,{workspaceId,courseId,actorUserId:x.internalUserId,userId,role:"student",active:false});reply.code(204);return}catch(e){return fail(reply,r,e)}});
 app.post("/v1/workspaces/:workspaceId/teach/resources",async(r,reply)=>{const{workspaceId}=r.params as any,b=teachingResourceSchema.parse(r.body),x=await principal(r,reply,workspaceId,"content.update");if(!x)return;try{reply.code(201);return await distributeTeachingResource(pool,omitUndefined({workspaceId,userId:x.internalUserId,courseId:b.courseId,nodeId:b.nodeId,title:b.title,state:b.state,releaseAt:b.releaseAt?new Date(b.releaseAt):undefined,audience:b.audience}))}catch(e){return fail(reply,r,e)}});
 app.post("/v1/workspaces/:workspaceId/teach/feedback",async(r,reply)=>{const{workspaceId}=r.params as any,b=teachingFeedbackSchema.parse(r.body),x=await principal(r,reply,workspaceId,"content.update");if(!x)return;try{return await upsertTeachingFeedback(pool,omitUndefined({workspaceId,userId:x.internalUserId,...b}))}catch(e){return fail(reply,r,e)}});
 app.post("/v1/workspaces/:workspaceId/teach/supervision",async(r,reply)=>{const{workspaceId}=r.params as any,b=supervisionSchema.parse(r.body),x=await principal(r,reply,workspaceId,"content.create");if(!x)return;try{reply.code(201);return await createSupervision(pool,{workspaceId,supervisorUserId:x.internalUserId,superviseeUserId:b.superviseeUserId,title:b.title})}catch(e){return fail(reply,r,e)}});
 app.get("/v1/workspaces/:workspaceId/teach/supervision/:relationshipId",async(r,reply)=>{const{workspaceId,relationshipId}=r.params as any,x=await principal(r,reply,workspaceId,"content.read");if(!x)return;try{return await supervisionDetail(pool,workspaceId,relationshipId,x.internalUserId)}catch(e){return fail(reply,r,e,404)}});
 app.post("/v1/workspaces/:workspaceId/teach/milestones",async(r,reply)=>{const{workspaceId}=r.params as any,b=supervisionMilestoneSchema.parse(r.body),x=await principal(r,reply,workspaceId,"content.update");if(!x)return;reply.code(201);return createSupervisionMilestone(pool,omitUndefined({workspaceId,userId:x.internalUserId,relationshipId:b.relationshipId,title:b.title,description:b.description,dueAt:b.dueAt?new Date(b.dueAt):undefined,linkedNodeId:b.linkedNodeId}))});
 app.post("/v1/workspaces/:workspaceId/teach/meetings",async(r,reply)=>{const{workspaceId}=r.params as any,b=supervisionMeetingSchema.parse(r.body),x=await principal(r,reply,workspaceId,"content.update");if(!x)return;try{reply.code(201);return await createSupervisionMeeting(pool,{workspaceId,userId:x.internalUserId,relationshipId:b.relationshipId,title:b.title,occurredAt:new Date(b.occurredAt),sharedSummary:b.sharedSummary,privateSupervisorNote:b.privateSupervisorNote})}catch(e){return fail(reply,r,e)}});
 app.post("/v1/workspaces/:workspaceId/teach/office-hours",async(r,reply)=>{const{workspaceId}=r.params as any,b=officeHourSchema.parse(r.body),x=await principal(r,reply,workspaceId,"content.create");if(!x)return;reply.code(201);return createOfficeHour(pool,omitUndefined({workspaceId,userId:x.internalUserId,courseId:b.courseId,startsAt:new Date(b.startsAt),endsAt:new Date(b.endsAt),timezone:b.timezone,location:b.location,meetingUrl:b.meetingUrl,capacity:b.capacity}))});
 app.post("/v1/workspaces/:workspaceId/teach/office-hour-bookings",async(r,reply)=>{const{workspaceId}=r.params as any,b=officeHourBookingSchema.parse(r.body),x=await principal(r,reply,workspaceId,"content.create");if(!x)return;try{reply.code(201);return await bookOfficeHour(pool,{workspaceId,userId:x.internalUserId,windowId:b.windowId,note:b.note})}catch(e){return fail(reply,r,e)}})
}