import { omitUndefined } from "./omit-undefined.js";
import type { AuthVerifier } from "@nexosophy/auth";
import {
  createTemplateRequestSchema,
  exportRequestSchema,
  importRequestSchema,
  instantiateTemplateRequestSchema,
  templateGalleryQuerySchema,
  transferActionSchema,
} from "@nexosophy/contracts";
import {
  cancelTransfer, createExportTransfer, createImportTransfer, createTemplateCapture,
  getTemplateDetail, getTransfer, instantiateTemplate, listImportableAssets,
  listTemplateCategories, listTemplates, listTransfers, retryTransfer,
} from "@nexosophy/db";
import type { StorageAdapter } from "@nexosophy/storage";
import type { FastifyInstance } from "fastify";
import {
  authorizeWorkspace, type DatabasePool, denyWorkspaceAuth,
  requireWorkspacePrincipal, sendWorkspaceError,
} from "./workspace-route-common.js";

function pub(t:any){return{id:t.id,workspaceId:t.workspaceId,kind:t.kind,durableJobId:t.durableJobId,sourceNodeId:t.sourceNodeId,sourceAssetId:t.sourceAssetId,destinationParentId:t.destinationParentId,format:t.format,fidelity:t.fidelity,artifactFilename:t.artifactFilename,artifactMime:t.artifactMime,manifestVersion:t.manifestVersion,resultRootNodeIds:t.resultRootNodeIds,jobStatus:t.jobStatus,progress:t.progress,createdAt:t.createdAt,updatedAt:t.updatedAt};}
function fail(reply:any,request:any,code:string,status=400){return sendWorkspaceError(reply,request.id,status,code,code.toLowerCase().replaceAll("_"," ").replace(/^./,(x:string)=>x.toUpperCase())+".");}

export async function registerTemplateTransferRoutes(app:FastifyInstance,pool:DatabasePool,storage:StorageAdapter|null,verifier:AuthVerifier=denyWorkspaceAuth){
 app.get("/v1/workspaces/:workspaceId/templates/categories",async(request,reply)=>{const{workspaceId}=request.params as any;const p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.read",request,reply)))return;return{items:await listTemplateCategories(pool,workspaceId)};});
 app.get("/v1/workspaces/:workspaceId/templates",async(request,reply)=>{const{workspaceId}=request.params as any,q=templateGalleryQuerySchema.parse(request.query);const p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.read",request,reply)))return;return{items:await listTemplates(pool,omitUndefined({workspaceId,userId:p.internalUserId,scope:q.scope,categoryId:q.categoryId,q:q.q,limit:q.limit}))};});
 app.post("/v1/workspaces/:workspaceId/templates",async(request,reply)=>{const{workspaceId}=request.params as any,b=createTemplateRequestSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.create",request,reply)))return;try{const x=await createTemplateCapture(pool,omitUndefined({workspaceId,actorUserId:p.internalUserId,scope:b.scope,categoryId:b.categoryId,name:b.name,description:b.description,sourceNodeId:b.sourceNodeId,roleSuggestions:b.roleSuggestions,variables:b.variables,publish:b.publish}));reply.code(202);return x;}catch(e){return fail(reply,request,e instanceof Error?e.message:"TEMPLATE_CREATE_FAILED");}});
 app.get("/v1/workspaces/:workspaceId/templates/:templateId",async(request,reply)=>{const{workspaceId,templateId}=request.params as any,version=Number((request.query as any)?.version||0)||undefined,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.read",request,reply)))return;try{return await getTemplateDetail(pool,omitUndefined({workspaceId,userId:p.internalUserId,templateId,version}));}catch(e){return fail(reply,request,e instanceof Error?e.message:"TEMPLATE_NOT_FOUND",404);}});
 app.post("/v1/workspaces/:workspaceId/templates/:templateId/instantiate",async(request,reply)=>{const{workspaceId,templateId}=request.params as any,b=instantiateTemplateRequestSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.create",request,reply)))return;try{const x=await instantiateTemplate(pool,omitUndefined({workspaceId,userId:p.internalUserId,templateId,destinationParentId:b.destinationParentId,values:b.values,version:b.version}));reply.code(202);return x;}catch(e){return fail(reply,request,e instanceof Error?e.message:"TEMPLATE_INSTANTIATE_FAILED");}});
 app.get("/v1/workspaces/:workspaceId/import-assets",async(request,reply)=>{const{workspaceId}=request.params as any,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.read",request,reply)))return;return{items:await listImportableAssets(pool,workspaceId)};});
 app.get("/v1/workspaces/:workspaceId/transfers",async(request,reply)=>{const{workspaceId}=request.params as any,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.read",request,reply)))return;return{items:(await listTransfers(pool,workspaceId)).map(pub)};});
 app.post("/v1/workspaces/:workspaceId/transfers/import",async(request,reply)=>{const{workspaceId}=request.params as any,b=importRequestSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.create",request,reply)))return;try{const x=await createImportTransfer(pool,omitUndefined({workspaceId,assetId:b.assetId,destinationParentId:b.destinationParentId,actorUserId:p.internalUserId,formatHint:b.formatHint}));reply.code(202);return pub(x);}catch(e){return fail(reply,request,e instanceof Error?e.message:"IMPORT_CREATE_FAILED");}});
 app.post("/v1/workspaces/:workspaceId/transfers/export",async(request,reply)=>{const{workspaceId}=request.params as any,b=exportRequestSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.read",request,reply)))return;try{const x=await createExportTransfer(pool,omitUndefined({workspaceId,actorUserId:p.internalUserId,scope:b.scope,nodeId:b.nodeId,format:b.format,includeRelations:b.includeRelations}));reply.code(202);return pub(x);}catch(e){return fail(reply,request,e instanceof Error?e.message:"EXPORT_CREATE_FAILED");}});
 app.get("/v1/workspaces/:workspaceId/transfers/:transferId",async(request,reply)=>{const{workspaceId,transferId}=request.params as any,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.read",request,reply)))return;try{return pub(await getTransfer(pool,workspaceId,transferId));}catch(e){return fail(reply,request,"TRANSFER_NOT_FOUND",404);}});
 app.post("/v1/workspaces/:workspaceId/transfers/:transferId/action",async(request,reply)=>{const{workspaceId,transferId}=request.params as any,b=transferActionSchema.parse(request.body),p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.update",request,reply)))return;try{if(b.action==="cancel")await cancelTransfer(pool,workspaceId,transferId);else await retryTransfer(pool,workspaceId,transferId);reply.code(204);return;}catch(e){return fail(reply,request,e instanceof Error?e.message:"TRANSFER_ACTION_FAILED");}});
 app.get("/v1/workspaces/:workspaceId/transfers/:transferId/download",async(request,reply)=>{if(!storage)return fail(reply,request,"STORAGE_UNAVAILABLE",503);const{workspaceId,transferId}=request.params as any,p=await requireWorkspacePrincipal(request,reply,verifier);if(!p)return;if(!(await authorizeWorkspace(pool,p,workspaceId,"content.read",request,reply)))return;try{const t=await getTransfer(pool,workspaceId,transferId);if(!t.artifactObjectKey)return fail(reply,request,"TRANSFER_ARTIFACT_NOT_READY",409);const signed=await storage.createDownloadUrl({key:t.artifactObjectKey,expiresInSeconds:600});return{url:signed.url,filename:t.artifactFilename,mimeType:t.artifactMime,expiresAt:new Date(Date.now()+600000).toISOString()};}catch(e){return fail(reply,request,e instanceof Error?e.message:"TRANSFER_NOT_FOUND",404);}});
}
