"use client";

type Encrypted={iv:ArrayBuffer;cipher:ArrayBuffer};
type QueueRow={operationId:string;workspaceId:string;type:string;targetId?:string;deviceId:string;encrypted:Encrypted;createdAt:string;attempts:number;lastError?:string};
type RecordRow={id:string;workspaceId:string;kind:string;targetId:string;encrypted:Encrypted;updatedAt:string;bytes:number};
type AttachmentRow={id:string;workspaceId:string;assetId:string;filename:string;mimeType:string;encrypted:Encrypted;bytes:number;updatedAt:string};

const DB="nexosophy-offline-v1",VERSION=1;
let opening:Promise<IDBDatabase>|null=null;
function req<T>(r:IDBRequest<T>){return new Promise<T>((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error??new Error("IndexedDB request failed"))})}
function txDone(t:IDBTransaction){return new Promise<void>((resolve,reject)=>{t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error??new Error("IndexedDB transaction failed"));t.onabort=()=>reject(t.error??new Error("IndexedDB transaction aborted"))})}
function openDb(){if(opening)return opening;opening=new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains("meta"))db.createObjectStore("meta");if(!db.objectStoreNames.contains("records")){const s=db.createObjectStore("records",{keyPath:"id"});s.createIndex("workspace","workspaceId")}if(!db.objectStoreNames.contains("queue")){const s=db.createObjectStore("queue",{keyPath:"operationId"});s.createIndex("workspace","workspaceId")}if(!db.objectStoreNames.contains("attachments")){const s=db.createObjectStore("attachments",{keyPath:"id"});s.createIndex("workspace","workspaceId")}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error??new Error("Unable to open offline database"))});return opening}
async function key(){const db=await openDb(),t=db.transaction("meta","readwrite"),s=t.objectStore("meta");let k=await req<CryptoKey|undefined>(s.get("aes-key"));if(!k){k=await crypto.subtle.generateKey({name:"AES-GCM",length:256},false,["encrypt","decrypt"]);s.put(k,"aes-key")}await txDone(t);return k}
async function enc(value:unknown):Promise<Encrypted>{const k=await key(),iv=crypto.getRandomValues(new Uint8Array(12)),plain=new TextEncoder().encode(JSON.stringify(value)),cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},k,plain);return{iv:iv.buffer,cipher}}
async function dec<T>(e:Encrypted):Promise<T>{const k=await key(),plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:new Uint8Array(e.iv)},k,e.cipher);return JSON.parse(new TextDecoder().decode(plain))as T}
async function encBytes(value:ArrayBuffer):Promise<Encrypted>{const k=await key(),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},k,value);return{iv:iv.buffer,cipher}}
async function decBytes(e:Encrypted){const k=await key();return crypto.subtle.decrypt({name:"AES-GCM",iv:new Uint8Array(e.iv)},k,e.cipher)}
async function meta<T>(name:string,create:()=>T|Promise<T>):Promise<T>{const db=await openDb(),read=db.transaction("meta","readonly").objectStore("meta"),existing=await req<T|undefined>(read.get(name));if(existing!==undefined)return existing;const value=await create(),t=db.transaction("meta","readwrite");t.objectStore("meta").put(value,name);await txDone(t);return value}
async function readMeta<T>(name:string){const db=await openDb();return req<T|undefined>(db.transaction("meta","readonly").objectStore("meta").get(name))}
async function writeMeta(name:string,value:unknown){const db=await openDb(),t=db.transaction("meta","readwrite");t.objectStore("meta").put(value,name);await txDone(t)}
type ClientPolicy={offlineAllowed:boolean;attachmentsAllowed:boolean;backgroundSyncAllowed:boolean;maxDeviceBytes:number};
const policies=new Map<string,{value:ClientPolicy;at:number}>();
export async function getClientOfflinePolicy(workspaceId:string,force=false):Promise<ClientPolicy>{const memory=policies.get(workspaceId);if(!force&&memory&&Date.now()-memory.at<60000)return memory.value;let value=await readMeta<ClientPolicy>("policy:"+workspaceId);if(navigator.onLine){try{const r=await fetch("/api/offline/"+workspaceId,{cache:"no-store"});if(r.ok){const x=await r.json()as any;value=x.policy;await writeMeta("policy:"+workspaceId,value)}}catch{}}const policy=value??{offlineAllowed:false,attachmentsAllowed:false,backgroundSyncAllowed:false,maxDeviceBytes:0};policies.set(workspaceId,{value:policy,at:Date.now()});if(!policy.offlineAllowed)await clearOfflineWorkspace(workspaceId);return policy}
export async function getOfflineDeviceId(){return meta("device-id",()=>crypto.randomUUID())}
export async function saveOfflineRecord(workspaceId:string,kind:string,targetId:string,value:unknown){const policy=await getClientOfflinePolicy(workspaceId);if(!policy.offlineAllowed)return;const encrypted=await enc(value),row:RecordRow={id:workspaceId+":"+kind+":"+targetId,workspaceId,kind,targetId,encrypted,updatedAt:new Date().toISOString(),bytes:encrypted.cipher.byteLength};const db=await openDb(),t=db.transaction("records","readwrite");t.objectStore("records").put(row);await txDone(t)}
export async function readOfflineRecord<T>(workspaceId:string,kind:string,targetId:string):Promise<T|null>{const db=await openDb(),row=await req<RecordRow|undefined>(db.transaction("records","readonly").objectStore("records").get(workspaceId+":"+kind+":"+targetId));return row?dec<T>(row.encrypted):null}
export async function listOfflineRecords(workspaceId:string){const db=await openDb(),rows=await req<RecordRow[]>(db.transaction("records","readonly").objectStore("records").index("workspace").getAll(workspaceId));const out=[];for(const row of rows){try{out.push({kind:row.kind,targetId:row.targetId,updatedAt:row.updatedAt,value:await dec<any>(row.encrypted)})}catch{}}return out}
async function queue(workspaceId:string,type:string,targetId:string|undefined,payload:any){const policy=await getClientOfflinePolicy(workspaceId);if(!policy.offlineAllowed)throw new Error("Workspace policy does not allow offline changes on this device.");const operationId=crypto.randomUUID(),deviceId=await getOfflineDeviceId(),encrypted=await enc(payload),row:QueueRow={operationId,workspaceId,type,deviceId,encrypted,createdAt:new Date().toISOString(),attempts:0};if(targetId!==undefined)row.targetId=targetId;const db=await openDb(),t=db.transaction("queue","readwrite");t.objectStore("queue").put(row);await txDone(t);window.dispatchEvent(new CustomEvent("nexosophy:offline-queue"));if(policy.backgroundSyncAllowed){try{const reg=await navigator.serviceWorker?.ready;(reg as any)?.sync?.register("nexosophy-sync")}catch{}}return operationId}
export async function queueDocumentSave(workspaceId:string,nodeId:string,expectedRevision:number,body:any){const db=await openDb(),rows=await req<QueueRow[]>(db.transaction("queue","readonly").objectStore("queue").index("workspace").getAll(workspaceId)),old=rows.filter(x=>x.type==="document.save"&&x.targetId===nodeId);if(old.length){const t=db.transaction("queue","readwrite"),s=t.objectStore("queue");for(const x of old)s.delete(x.operationId);await txDone(t)}return queue(workspaceId,"document.save",nodeId,{expectedRevision,body})}
export async function queueTaskMutation(workspaceId:string,body:Record<string,any>){if(body.action==="createTask"){const{action,...payload}=body;return queue(workspaceId,"task.create",undefined,payload)}if(body.action==="updateTask"||body.action==="completeTask"){const targetId=String(body.taskId??"");if(!targetId)throw new Error("Task ID is required for offline update.");const{action,taskId,...rest}=body,payload=body.action==="completeTask"?{...rest,status:"done"}:rest;if(!Number.isInteger(payload.expectedVersion))throw new Error("Task version is required for offline update.");return queue(workspaceId,"task.update",targetId,payload)}throw new Error("This task action is not available offline.")}
async function queued(workspaceId:string){const db=await openDb(),rows=await req<QueueRow[]>(db.transaction("queue","readonly").objectStore("queue").index("workspace").getAll(workspaceId)),out=[];for(const row of rows){out.push({operationId:row.operationId,deviceId:row.deviceId,type:row.type,targetId:row.targetId,payload:await dec<any>(row.encrypted),createdAt:row.createdAt,attempts:row.attempts})}return out.sort((a,b)=>a.createdAt.localeCompare(b.createdAt))}
async function removeOps(ids:string[]){if(!ids.length)return;const db=await openDb(),t=db.transaction("queue","readwrite"),s=t.objectStore("queue");for(const id of ids)s.delete(id);await txDone(t)}
async function markOps(ids:string[],error:string){const db=await openDb(),t=db.transaction("queue","readwrite"),s=t.objectStore("queue");for(const id of ids){const row=await req<QueueRow|undefined>(s.get(id));if(row)s.put({...row,attempts:row.attempts+1,lastError:error.slice(0,500)})}await txDone(t)}
export async function offlineUsage(workspaceId:string){const db=await openDb(),[records,attachments,queueRows]=await Promise.all([req<RecordRow[]>(db.transaction("records","readonly").objectStore("records").index("workspace").getAll(workspaceId)),req<AttachmentRow[]>(db.transaction("attachments","readonly").objectStore("attachments").index("workspace").getAll(workspaceId)),req<QueueRow[]>(db.transaction("queue","readonly").objectStore("queue").index("workspace").getAll(workspaceId))]);return{bytes:records.reduce((n,x)=>n+x.bytes,0)+attachments.reduce((n,x)=>n+x.bytes,0)+queueRows.reduce((n,x)=>n+x.encrypted.cipher.byteLength,0),recordCount:records.length,attachmentCount:attachments.length,queuedCount:queueRows.length}}
export async function syncOfflineWorkspace(workspaceId:string){if(!navigator.onLine)return{offline:true};const policy=await getClientOfflinePolicy(workspaceId,true);if(!policy.offlineAllowed)return{disabled:true};const operations=await queued(workspaceId),usage=await offlineUsage(workspaceId),deviceId=await getOfflineDeviceId(),device={deviceId,label:(navigator as Navigator&{userAgentData?:{platform?:string}}).userAgentData?.platform??navigator.platform??"Browser",platform:navigator.userAgent,appVersion:"web-pwa",reportedBytes:usage.bytes};const response=await fetch("/api/offline/"+workspaceId,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"sync",device,operations:operations.map(({createdAt,attempts,...x})=>x)})});if(!response.ok){const x=await response.json().catch(()=>null)as any;await markOps(operations.map(x=>x.operationId),x?.error?.message??"Sync failed");throw new Error(x?.error?.message??"Offline sync failed.")}const result=await response.json()as any,done=(result.results??[]).filter((x:any)=>x.status==="applied"||x.status==="conflict").map((x:any)=>x.operationId);await removeOps(done);window.dispatchEvent(new CustomEvent("nexosophy:offline-synced",{detail:result}));return result}
export async function cacheAttachmentOffline(workspaceId:string,assetId:string,filename:string,mimeType:string,maxBytes:number){const policy=await getClientOfflinePolicy(workspaceId,true);if(!policy.offlineAllowed||!policy.attachmentsAllowed)throw new Error("Workspace policy does not allow offline attachments.");const usage=await offlineUsage(workspaceId),signed=await fetch("/api/uploads/"+workspaceId,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"download",assetId})});if(!signed.ok)throw new Error("Unable to authorize attachment download.");const{url}=await signed.json()as{url:string},r=await fetch(url);if(!r.ok)throw new Error("Unable to download attachment for offline use.");const length=Number(r.headers.get("content-length")??0);if(length>32*1024*1024)throw new Error("A single offline attachment is limited to 32 MB to protect mobile memory.");const bytes=await r.arrayBuffer();if(bytes.byteLength>32*1024*1024)throw new Error("A single offline attachment is limited to 32 MB to protect mobile memory.");if(usage.bytes+bytes.byteLength>maxBytes)throw new Error("Offline device quota would be exceeded.");const encrypted=await encBytes(bytes),row:AttachmentRow={id:workspaceId+":"+assetId,workspaceId,assetId,filename,mimeType,encrypted,bytes:encrypted.cipher.byteLength,updatedAt:new Date().toISOString()},db=await openDb(),t=db.transaction("attachments","readwrite");t.objectStore("attachments").put(row);await txDone(t);const deviceId=await getOfflineDeviceId();const pin=await fetch("/api/offline/"+workspaceId,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"pin",deviceId,resourceType:"attachment",resourceId:assetId,pinned:true})});if(!pin.ok){await removeOfflineAttachment(workspaceId,assetId,false);const x=await pin.json().catch(()=>null)as any;throw new Error(x?.error?.message??"Workspace policy rejected offline attachment.")}return{bytes:bytes.byteLength}}
export async function removeOfflineAttachment(workspaceId:string,assetId:string,syncPin=true){const db=await openDb(),t=db.transaction("attachments","readwrite");t.objectStore("attachments").delete(workspaceId+":"+assetId);await txDone(t);if(syncPin&&navigator.onLine){const deviceId=await getOfflineDeviceId();await fetch("/api/offline/"+workspaceId,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"pin",deviceId,resourceType:"attachment",resourceId:assetId,pinned:false})}).catch(()=>undefined)}}
export async function openOfflineAttachment(workspaceId:string,assetId:string){const db=await openDb(),row=await req<AttachmentRow|undefined>(db.transaction("attachments","readonly").objectStore("attachments").get(workspaceId+":"+assetId));if(!row)return null;const bytes=await decBytes(row.encrypted);return{url:URL.createObjectURL(new Blob([bytes],{type:row.mimeType})),filename:row.filename,mimeType:row.mimeType}}
export async function clearOfflineWorkspace(workspaceId:string){const db=await openDb();for(const store of["records","queue","attachments"]){const t=db.transaction(store,"readwrite"),s=t.objectStore(store),index=s.index("workspace"),keys=await req<IDBValidKey[]>(index.getAllKeys(workspaceId));for(const k of keys)s.delete(k);await txDone(t)}}